// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netapp

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/commontypesv6"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// NetApp Elastic Capacity Pool resource
//
// Uses Azure REST API version 2025-09-01-preview.
//
// Other available API versions: 2025-12-15-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native netapp [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
type ElasticCapacityPool struct {
	pulumi.CustomResourceState

	// The Azure API version of the resource.
	AzureApiVersion pulumi.StringOutput `pulumi:"azureApiVersion"`
	// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
	ETag pulumi.StringOutput `pulumi:"eTag"`
	// The geo-location where the resource lives
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of the resource
	Name pulumi.StringOutput `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties ElasticCapacityPoolPropertiesResponseOutput `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData commontypesv6.SystemDataResponseOutput `pulumi:"systemData"`
	// Resource tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type pulumi.StringOutput `pulumi:"type"`
	// The availability zones.
	Zones pulumi.StringArrayOutput `pulumi:"zones"`
}

// NewElasticCapacityPool registers a new resource with the given unique name, arguments, and options.
func NewElasticCapacityPool(ctx *pulumi.Context,
	name string, args *ElasticCapacityPoolArgs, opts ...pulumi.ResourceOption) (*ElasticCapacityPool, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountName == nil {
		return nil, errors.New("invalid value for required argument 'AccountName'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type: pulumi.String("azure-native:netapp/v20250901preview:ElasticCapacityPool"),
		},
		{
			Type: pulumi.String("azure-native:netapp/v20251215preview:ElasticCapacityPool"),
		},
	})
	opts = append(opts, aliases)
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ElasticCapacityPool
	err := ctx.RegisterResource("azure-native:netapp:ElasticCapacityPool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetElasticCapacityPool gets an existing ElasticCapacityPool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetElasticCapacityPool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ElasticCapacityPoolState, opts ...pulumi.ResourceOption) (*ElasticCapacityPool, error) {
	var resource ElasticCapacityPool
	err := ctx.ReadResource("azure-native:netapp:ElasticCapacityPool", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ElasticCapacityPool resources.
type elasticCapacityPoolState struct {
}

type ElasticCapacityPoolState struct {
}

func (ElasticCapacityPoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*elasticCapacityPoolState)(nil)).Elem()
}

type elasticCapacityPoolArgs struct {
	// The name of the ElasticAccount
	AccountName string `pulumi:"accountName"`
	// The geo-location where the resource lives
	Location *string `pulumi:"location"`
	// The name of the ElasticCapacityPool
	PoolName *string `pulumi:"poolName"`
	// The resource-specific properties for this resource.
	Properties *ElasticCapacityPoolProperties `pulumi:"properties"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// Resource tags.
	Tags map[string]string `pulumi:"tags"`
	// The availability zones.
	Zones []string `pulumi:"zones"`
}

// The set of arguments for constructing a ElasticCapacityPool resource.
type ElasticCapacityPoolArgs struct {
	// The name of the ElasticAccount
	AccountName pulumi.StringInput
	// The geo-location where the resource lives
	Location pulumi.StringPtrInput
	// The name of the ElasticCapacityPool
	PoolName pulumi.StringPtrInput
	// The resource-specific properties for this resource.
	Properties ElasticCapacityPoolPropertiesPtrInput
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput
	// Resource tags.
	Tags pulumi.StringMapInput
	// The availability zones.
	Zones pulumi.StringArrayInput
}

func (ElasticCapacityPoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*elasticCapacityPoolArgs)(nil)).Elem()
}

type ElasticCapacityPoolInput interface {
	pulumi.Input

	ToElasticCapacityPoolOutput() ElasticCapacityPoolOutput
	ToElasticCapacityPoolOutputWithContext(ctx context.Context) ElasticCapacityPoolOutput
}

func (*ElasticCapacityPool) ElementType() reflect.Type {
	return reflect.TypeOf((**ElasticCapacityPool)(nil)).Elem()
}

func (i *ElasticCapacityPool) ToElasticCapacityPoolOutput() ElasticCapacityPoolOutput {
	return i.ToElasticCapacityPoolOutputWithContext(context.Background())
}

func (i *ElasticCapacityPool) ToElasticCapacityPoolOutputWithContext(ctx context.Context) ElasticCapacityPoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ElasticCapacityPoolOutput)
}

type ElasticCapacityPoolOutput struct{ *pulumi.OutputState }

func (ElasticCapacityPoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ElasticCapacityPool)(nil)).Elem()
}

func (o ElasticCapacityPoolOutput) ToElasticCapacityPoolOutput() ElasticCapacityPoolOutput {
	return o
}

func (o ElasticCapacityPoolOutput) ToElasticCapacityPoolOutputWithContext(ctx context.Context) ElasticCapacityPoolOutput {
	return o
}

// The Azure API version of the resource.
func (o ElasticCapacityPoolOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringOutput { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
func (o ElasticCapacityPoolOutput) ETag() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringOutput { return v.ETag }).(pulumi.StringOutput)
}

// The geo-location where the resource lives
func (o ElasticCapacityPoolOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of the resource
func (o ElasticCapacityPoolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o ElasticCapacityPoolOutput) Properties() ElasticCapacityPoolPropertiesResponseOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) ElasticCapacityPoolPropertiesResponseOutput { return v.Properties }).(ElasticCapacityPoolPropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o ElasticCapacityPoolOutput) SystemData() commontypesv6.SystemDataResponseOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) commontypesv6.SystemDataResponseOutput { return v.SystemData }).(commontypesv6.SystemDataResponseOutput)
}

// Resource tags.
func (o ElasticCapacityPoolOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o ElasticCapacityPoolOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The availability zones.
func (o ElasticCapacityPoolOutput) Zones() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ElasticCapacityPool) pulumi.StringArrayOutput { return v.Zones }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticCapacityPoolOutput{})
}
