// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netapp

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/commontypesv6"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// NetApp elastic backup vault resource
//
// Uses Azure REST API version 2025-09-01-preview.
//
// Other available API versions: 2025-12-15-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native netapp [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
type ElasticBackupVault struct {
	pulumi.CustomResourceState

	// The Azure API version of the resource.
	AzureApiVersion pulumi.StringOutput `pulumi:"azureApiVersion"`
	// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
	ETag pulumi.StringOutput `pulumi:"eTag"`
	// The geo-location where the resource lives
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of the resource
	Name pulumi.StringOutput `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties ElasticBackupVaultPropertiesResponseOutput `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData commontypesv6.SystemDataResponseOutput `pulumi:"systemData"`
	// Resource tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewElasticBackupVault registers a new resource with the given unique name, arguments, and options.
func NewElasticBackupVault(ctx *pulumi.Context,
	name string, args *ElasticBackupVaultArgs, opts ...pulumi.ResourceOption) (*ElasticBackupVault, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountName == nil {
		return nil, errors.New("invalid value for required argument 'AccountName'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type: pulumi.String("azure-native:netapp/v20250901preview:ElasticBackupVault"),
		},
		{
			Type: pulumi.String("azure-native:netapp/v20251215preview:ElasticBackupVault"),
		},
	})
	opts = append(opts, aliases)
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ElasticBackupVault
	err := ctx.RegisterResource("azure-native:netapp:ElasticBackupVault", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetElasticBackupVault gets an existing ElasticBackupVault resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetElasticBackupVault(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ElasticBackupVaultState, opts ...pulumi.ResourceOption) (*ElasticBackupVault, error) {
	var resource ElasticBackupVault
	err := ctx.ReadResource("azure-native:netapp:ElasticBackupVault", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ElasticBackupVault resources.
type elasticBackupVaultState struct {
}

type ElasticBackupVaultState struct {
}

func (ElasticBackupVaultState) ElementType() reflect.Type {
	return reflect.TypeOf((*elasticBackupVaultState)(nil)).Elem()
}

type elasticBackupVaultArgs struct {
	// The name of the ElasticAccount
	AccountName string `pulumi:"accountName"`
	// The name of the ElasticBackupVault
	BackupVaultName *string `pulumi:"backupVaultName"`
	// The geo-location where the resource lives
	Location *string `pulumi:"location"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// Resource tags.
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a ElasticBackupVault resource.
type ElasticBackupVaultArgs struct {
	// The name of the ElasticAccount
	AccountName pulumi.StringInput
	// The name of the ElasticBackupVault
	BackupVaultName pulumi.StringPtrInput
	// The geo-location where the resource lives
	Location pulumi.StringPtrInput
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput
	// Resource tags.
	Tags pulumi.StringMapInput
}

func (ElasticBackupVaultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*elasticBackupVaultArgs)(nil)).Elem()
}

type ElasticBackupVaultInput interface {
	pulumi.Input

	ToElasticBackupVaultOutput() ElasticBackupVaultOutput
	ToElasticBackupVaultOutputWithContext(ctx context.Context) ElasticBackupVaultOutput
}

func (*ElasticBackupVault) ElementType() reflect.Type {
	return reflect.TypeOf((**ElasticBackupVault)(nil)).Elem()
}

func (i *ElasticBackupVault) ToElasticBackupVaultOutput() ElasticBackupVaultOutput {
	return i.ToElasticBackupVaultOutputWithContext(context.Background())
}

func (i *ElasticBackupVault) ToElasticBackupVaultOutputWithContext(ctx context.Context) ElasticBackupVaultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ElasticBackupVaultOutput)
}

type ElasticBackupVaultOutput struct{ *pulumi.OutputState }

func (ElasticBackupVaultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ElasticBackupVault)(nil)).Elem()
}

func (o ElasticBackupVaultOutput) ToElasticBackupVaultOutput() ElasticBackupVaultOutput {
	return o
}

func (o ElasticBackupVaultOutput) ToElasticBackupVaultOutputWithContext(ctx context.Context) ElasticBackupVaultOutput {
	return o
}

// The Azure API version of the resource.
func (o ElasticBackupVaultOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringOutput { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
func (o ElasticBackupVaultOutput) ETag() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringOutput { return v.ETag }).(pulumi.StringOutput)
}

// The geo-location where the resource lives
func (o ElasticBackupVaultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of the resource
func (o ElasticBackupVaultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o ElasticBackupVaultOutput) Properties() ElasticBackupVaultPropertiesResponseOutput {
	return o.ApplyT(func(v *ElasticBackupVault) ElasticBackupVaultPropertiesResponseOutput { return v.Properties }).(ElasticBackupVaultPropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o ElasticBackupVaultOutput) SystemData() commontypesv6.SystemDataResponseOutput {
	return o.ApplyT(func(v *ElasticBackupVault) commontypesv6.SystemDataResponseOutput { return v.SystemData }).(commontypesv6.SystemDataResponseOutput)
}

// Resource tags.
func (o ElasticBackupVaultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o ElasticBackupVaultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *ElasticBackupVault) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticBackupVaultOutput{})
}
