// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20241002preview

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:app/v20241002preview:AppResiliency":
		r = &AppResiliency{}
	case "azure-native:app/v20241002preview:Build":
		r = &Build{}
	case "azure-native:app/v20241002preview:Builder":
		r = &Builder{}
	case "azure-native:app/v20241002preview:Certificate":
		r = &Certificate{}
	case "azure-native:app/v20241002preview:ConnectedEnvironment":
		r = &ConnectedEnvironment{}
	case "azure-native:app/v20241002preview:ConnectedEnvironmentsCertificate":
		r = &ConnectedEnvironmentsCertificate{}
	case "azure-native:app/v20241002preview:ConnectedEnvironmentsDaprComponent":
		r = &ConnectedEnvironmentsDaprComponent{}
	case "azure-native:app/v20241002preview:ConnectedEnvironmentsStorage":
		r = &ConnectedEnvironmentsStorage{}
	case "azure-native:app/v20241002preview:ContainerApp":
		r = &ContainerApp{}
	case "azure-native:app/v20241002preview:ContainerAppsAuthConfig":
		r = &ContainerAppsAuthConfig{}
	case "azure-native:app/v20241002preview:ContainerAppsSessionPool":
		r = &ContainerAppsSessionPool{}
	case "azure-native:app/v20241002preview:ContainerAppsSourceControl":
		r = &ContainerAppsSourceControl{}
	case "azure-native:app/v20241002preview:DaprComponent":
		r = &DaprComponent{}
	case "azure-native:app/v20241002preview:DaprComponentResiliencyPolicy":
		r = &DaprComponentResiliencyPolicy{}
	case "azure-native:app/v20241002preview:DaprSubscription":
		r = &DaprSubscription{}
	case "azure-native:app/v20241002preview:DotNetComponent":
		r = &DotNetComponent{}
	case "azure-native:app/v20241002preview:HttpRouteConfig":
		r = &HttpRouteConfig{}
	case "azure-native:app/v20241002preview:JavaComponent":
		r = &JavaComponent{}
	case "azure-native:app/v20241002preview:Job":
		r = &Job{}
	case "azure-native:app/v20241002preview:LogicApp":
		r = &LogicApp{}
	case "azure-native:app/v20241002preview:MaintenanceConfiguration":
		r = &MaintenanceConfiguration{}
	case "azure-native:app/v20241002preview:ManagedCertificate":
		r = &ManagedCertificate{}
	case "azure-native:app/v20241002preview:ManagedEnvironment":
		r = &ManagedEnvironment{}
	case "azure-native:app/v20241002preview:ManagedEnvironmentPrivateEndpointConnection":
		r = &ManagedEnvironmentPrivateEndpointConnection{}
	case "azure-native:app/v20241002preview:ManagedEnvironmentsStorage":
		r = &ManagedEnvironmentsStorage{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := utilities.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"app/v20241002preview",
		&module{version},
	)
}
