// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20230701preview

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The operation returns properties of a MachinePool.
func LookupMachinePool(ctx *pulumi.Context, args *LookupMachinePoolArgs, opts ...pulumi.InvokeOption) (*LookupMachinePoolResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupMachinePoolResult
	err := ctx.Invoke("azure-native:redhatopenshift/v20230701preview:getMachinePool", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupMachinePoolArgs struct {
	// The name of the MachinePool resource.
	ChildResourceName string `pulumi:"childResourceName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The name of the OpenShift cluster resource.
	ResourceName string `pulumi:"resourceName"`
}

// MachinePool represents a MachinePool
type LookupMachinePoolResult struct {
	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	Id string `pulumi:"id"`
	// The name of the resource
	Name      string  `pulumi:"name"`
	Resources *string `pulumi:"resources"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type string `pulumi:"type"`
}

func LookupMachinePoolOutput(ctx *pulumi.Context, args LookupMachinePoolOutputArgs, opts ...pulumi.InvokeOption) LookupMachinePoolResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupMachinePoolResultOutput, error) {
			args := v.(LookupMachinePoolArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:redhatopenshift/v20230701preview:getMachinePool", args, LookupMachinePoolResultOutput{}, options).(LookupMachinePoolResultOutput), nil
		}).(LookupMachinePoolResultOutput)
}

type LookupMachinePoolOutputArgs struct {
	// The name of the MachinePool resource.
	ChildResourceName pulumi.StringInput `pulumi:"childResourceName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The name of the OpenShift cluster resource.
	ResourceName pulumi.StringInput `pulumi:"resourceName"`
}

func (LookupMachinePoolOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMachinePoolArgs)(nil)).Elem()
}

// MachinePool represents a MachinePool
type LookupMachinePoolResultOutput struct{ *pulumi.OutputState }

func (LookupMachinePoolResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMachinePoolResult)(nil)).Elem()
}

func (o LookupMachinePoolResultOutput) ToLookupMachinePoolResultOutput() LookupMachinePoolResultOutput {
	return o
}

func (o LookupMachinePoolResultOutput) ToLookupMachinePoolResultOutputWithContext(ctx context.Context) LookupMachinePoolResultOutput {
	return o
}

// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
func (o LookupMachinePoolResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMachinePoolResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the resource
func (o LookupMachinePoolResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMachinePoolResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupMachinePoolResultOutput) Resources() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMachinePoolResult) *string { return v.Resources }).(pulumi.StringPtrOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o LookupMachinePoolResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupMachinePoolResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o LookupMachinePoolResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMachinePoolResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMachinePoolResultOutput{})
}
