// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20220101preview

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Governance rule over a given scope
func LookupSecurityConnectorGovernanceRule(ctx *pulumi.Context, args *LookupSecurityConnectorGovernanceRuleArgs, opts ...pulumi.InvokeOption) (*LookupSecurityConnectorGovernanceRuleResult, error) {
	var rv LookupSecurityConnectorGovernanceRuleResult
	err := ctx.Invoke("azure-native:security/v20220101preview:getSecurityConnectorGovernanceRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupSecurityConnectorGovernanceRuleArgs struct {
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The governance rule key - unique key for the standard governance rule (GUID)
	RuleId string `pulumi:"ruleId"`
	// The security connector name.
	SecurityConnectorName string `pulumi:"securityConnectorName"`
}

// Governance rule over a given scope
type LookupSecurityConnectorGovernanceRuleResult struct {
	// Description of the governance rule
	Description *string `pulumi:"description"`
	// Display name of the governance rule
	DisplayName string `pulumi:"displayName"`
	// Excluded scopes, filter out the descendants of the scope (on management scopes)
	ExcludedScopes []string `pulumi:"excludedScopes"`
	// The email notifications settings for the governance rule, states whether to disable notifications for mangers and owners
	GovernanceEmailNotification *GovernanceRuleEmailNotificationResponse `pulumi:"governanceEmailNotification"`
	// Resource Id
	Id string `pulumi:"id"`
	// Defines whether the rule is management scope rule (master connector as a single scope or management scope)
	IncludeMemberScopes *bool `pulumi:"includeMemberScopes"`
	// Defines whether the rule is active/inactive
	IsDisabled *bool `pulumi:"isDisabled"`
	// Defines whether there is a grace period on the governance rule
	IsGracePeriod *bool `pulumi:"isGracePeriod"`
	// The governance rule metadata
	Metadata *GovernanceRuleMetadataResponse `pulumi:"metadata"`
	// Resource name
	Name string `pulumi:"name"`
	// The owner source for the governance rule - e.g. Manually by user@contoso.com - see example
	OwnerSource GovernanceRuleOwnerSourceResponse `pulumi:"ownerSource"`
	// Governance rule remediation timeframe - this is the time that will affect on the grace-period duration e.g. 7.00:00:00 - means 7 days
	RemediationTimeframe *string `pulumi:"remediationTimeframe"`
	// The governance rule priority, priority to the lower number. Rules with the same priority on the same subscription will not be allowed
	RulePriority int `pulumi:"rulePriority"`
	// The rule type of the governance rule, defines the source of the rule e.g. Integrated
	RuleType string `pulumi:"ruleType"`
	// The governance rule source, what the rule affects, e.g. Assessments
	SourceResourceType string `pulumi:"sourceResourceType"`
	// The tenantId (GUID)
	TenantId string `pulumi:"tenantId"`
	// Resource type
	Type string `pulumi:"type"`
}

func LookupSecurityConnectorGovernanceRuleOutput(ctx *pulumi.Context, args LookupSecurityConnectorGovernanceRuleOutputArgs, opts ...pulumi.InvokeOption) LookupSecurityConnectorGovernanceRuleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSecurityConnectorGovernanceRuleResult, error) {
			args := v.(LookupSecurityConnectorGovernanceRuleArgs)
			r, err := LookupSecurityConnectorGovernanceRule(ctx, &args, opts...)
			var s LookupSecurityConnectorGovernanceRuleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSecurityConnectorGovernanceRuleResultOutput)
}

type LookupSecurityConnectorGovernanceRuleOutputArgs struct {
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The governance rule key - unique key for the standard governance rule (GUID)
	RuleId pulumi.StringInput `pulumi:"ruleId"`
	// The security connector name.
	SecurityConnectorName pulumi.StringInput `pulumi:"securityConnectorName"`
}

func (LookupSecurityConnectorGovernanceRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityConnectorGovernanceRuleArgs)(nil)).Elem()
}

// Governance rule over a given scope
type LookupSecurityConnectorGovernanceRuleResultOutput struct{ *pulumi.OutputState }

func (LookupSecurityConnectorGovernanceRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityConnectorGovernanceRuleResult)(nil)).Elem()
}

func (o LookupSecurityConnectorGovernanceRuleResultOutput) ToLookupSecurityConnectorGovernanceRuleResultOutput() LookupSecurityConnectorGovernanceRuleResultOutput {
	return o
}

func (o LookupSecurityConnectorGovernanceRuleResultOutput) ToLookupSecurityConnectorGovernanceRuleResultOutputWithContext(ctx context.Context) LookupSecurityConnectorGovernanceRuleResultOutput {
	return o
}

// Description of the governance rule
func (o LookupSecurityConnectorGovernanceRuleResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Display name of the governance rule
func (o LookupSecurityConnectorGovernanceRuleResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// Excluded scopes, filter out the descendants of the scope (on management scopes)
func (o LookupSecurityConnectorGovernanceRuleResultOutput) ExcludedScopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) []string { return v.ExcludedScopes }).(pulumi.StringArrayOutput)
}

// The email notifications settings for the governance rule, states whether to disable notifications for mangers and owners
func (o LookupSecurityConnectorGovernanceRuleResultOutput) GovernanceEmailNotification() GovernanceRuleEmailNotificationResponsePtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *GovernanceRuleEmailNotificationResponse {
		return v.GovernanceEmailNotification
	}).(GovernanceRuleEmailNotificationResponsePtrOutput)
}

// Resource Id
func (o LookupSecurityConnectorGovernanceRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Defines whether the rule is management scope rule (master connector as a single scope or management scope)
func (o LookupSecurityConnectorGovernanceRuleResultOutput) IncludeMemberScopes() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *bool { return v.IncludeMemberScopes }).(pulumi.BoolPtrOutput)
}

// Defines whether the rule is active/inactive
func (o LookupSecurityConnectorGovernanceRuleResultOutput) IsDisabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *bool { return v.IsDisabled }).(pulumi.BoolPtrOutput)
}

// Defines whether there is a grace period on the governance rule
func (o LookupSecurityConnectorGovernanceRuleResultOutput) IsGracePeriod() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *bool { return v.IsGracePeriod }).(pulumi.BoolPtrOutput)
}

// The governance rule metadata
func (o LookupSecurityConnectorGovernanceRuleResultOutput) Metadata() GovernanceRuleMetadataResponsePtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *GovernanceRuleMetadataResponse { return v.Metadata }).(GovernanceRuleMetadataResponsePtrOutput)
}

// Resource name
func (o LookupSecurityConnectorGovernanceRuleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.Name }).(pulumi.StringOutput)
}

// The owner source for the governance rule - e.g. Manually by user@contoso.com - see example
func (o LookupSecurityConnectorGovernanceRuleResultOutput) OwnerSource() GovernanceRuleOwnerSourceResponseOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) GovernanceRuleOwnerSourceResponse {
		return v.OwnerSource
	}).(GovernanceRuleOwnerSourceResponseOutput)
}

// Governance rule remediation timeframe - this is the time that will affect on the grace-period duration e.g. 7.00:00:00 - means 7 days
func (o LookupSecurityConnectorGovernanceRuleResultOutput) RemediationTimeframe() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) *string { return v.RemediationTimeframe }).(pulumi.StringPtrOutput)
}

// The governance rule priority, priority to the lower number. Rules with the same priority on the same subscription will not be allowed
func (o LookupSecurityConnectorGovernanceRuleResultOutput) RulePriority() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) int { return v.RulePriority }).(pulumi.IntOutput)
}

// The rule type of the governance rule, defines the source of the rule e.g. Integrated
func (o LookupSecurityConnectorGovernanceRuleResultOutput) RuleType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.RuleType }).(pulumi.StringOutput)
}

// The governance rule source, what the rule affects, e.g. Assessments
func (o LookupSecurityConnectorGovernanceRuleResultOutput) SourceResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.SourceResourceType }).(pulumi.StringOutput)
}

// The tenantId (GUID)
func (o LookupSecurityConnectorGovernanceRuleResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.TenantId }).(pulumi.StringOutput)
}

// Resource type
func (o LookupSecurityConnectorGovernanceRuleResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityConnectorGovernanceRuleResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecurityConnectorGovernanceRuleResultOutput{})
}
