// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agfoodplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v3/commontypesv4"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = utilities.GetEnvOrDefault

// ApiKeyAuthCredentials class for ApiKey based Auth.
type ApiKeyAuthCredentials struct {
	// Properties of the key vault.
	ApiKey KeyVaultProperties `pulumi:"apiKey"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'ApiKeyAuthCredentials'.
	Kind string `pulumi:"kind"`
}

// ApiKeyAuthCredentialsInput is an input type that accepts ApiKeyAuthCredentialsArgs and ApiKeyAuthCredentialsOutput values.
// You can construct a concrete instance of `ApiKeyAuthCredentialsInput` via:
//
//	ApiKeyAuthCredentialsArgs{...}
type ApiKeyAuthCredentialsInput interface {
	pulumi.Input

	ToApiKeyAuthCredentialsOutput() ApiKeyAuthCredentialsOutput
	ToApiKeyAuthCredentialsOutputWithContext(context.Context) ApiKeyAuthCredentialsOutput
}

// ApiKeyAuthCredentials class for ApiKey based Auth.
type ApiKeyAuthCredentialsArgs struct {
	// Properties of the key vault.
	ApiKey KeyVaultPropertiesInput `pulumi:"apiKey"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'ApiKeyAuthCredentials'.
	Kind pulumi.StringInput `pulumi:"kind"`
}

func (ApiKeyAuthCredentialsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiKeyAuthCredentials)(nil)).Elem()
}

func (i ApiKeyAuthCredentialsArgs) ToApiKeyAuthCredentialsOutput() ApiKeyAuthCredentialsOutput {
	return i.ToApiKeyAuthCredentialsOutputWithContext(context.Background())
}

func (i ApiKeyAuthCredentialsArgs) ToApiKeyAuthCredentialsOutputWithContext(ctx context.Context) ApiKeyAuthCredentialsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiKeyAuthCredentialsOutput)
}

// ApiKeyAuthCredentials class for ApiKey based Auth.
type ApiKeyAuthCredentialsOutput struct{ *pulumi.OutputState }

func (ApiKeyAuthCredentialsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiKeyAuthCredentials)(nil)).Elem()
}

func (o ApiKeyAuthCredentialsOutput) ToApiKeyAuthCredentialsOutput() ApiKeyAuthCredentialsOutput {
	return o
}

func (o ApiKeyAuthCredentialsOutput) ToApiKeyAuthCredentialsOutputWithContext(ctx context.Context) ApiKeyAuthCredentialsOutput {
	return o
}

// Properties of the key vault.
func (o ApiKeyAuthCredentialsOutput) ApiKey() KeyVaultPropertiesOutput {
	return o.ApplyT(func(v ApiKeyAuthCredentials) KeyVaultProperties { return v.ApiKey }).(KeyVaultPropertiesOutput)
}

// Enum for different types of AuthCredentials supported.
// Expected value is 'ApiKeyAuthCredentials'.
func (o ApiKeyAuthCredentialsOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v ApiKeyAuthCredentials) string { return v.Kind }).(pulumi.StringOutput)
}

// ApiKeyAuthCredentials class for ApiKey based Auth.
type ApiKeyAuthCredentialsResponse struct {
	// Properties of the key vault.
	ApiKey KeyVaultPropertiesResponse `pulumi:"apiKey"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'ApiKeyAuthCredentials'.
	Kind string `pulumi:"kind"`
}

// ApiKeyAuthCredentials class for ApiKey based Auth.
type ApiKeyAuthCredentialsResponseOutput struct{ *pulumi.OutputState }

func (ApiKeyAuthCredentialsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiKeyAuthCredentialsResponse)(nil)).Elem()
}

func (o ApiKeyAuthCredentialsResponseOutput) ToApiKeyAuthCredentialsResponseOutput() ApiKeyAuthCredentialsResponseOutput {
	return o
}

func (o ApiKeyAuthCredentialsResponseOutput) ToApiKeyAuthCredentialsResponseOutputWithContext(ctx context.Context) ApiKeyAuthCredentialsResponseOutput {
	return o
}

// Properties of the key vault.
func (o ApiKeyAuthCredentialsResponseOutput) ApiKey() KeyVaultPropertiesResponseOutput {
	return o.ApplyT(func(v ApiKeyAuthCredentialsResponse) KeyVaultPropertiesResponse { return v.ApiKey }).(KeyVaultPropertiesResponseOutput)
}

// Enum for different types of AuthCredentials supported.
// Expected value is 'ApiKeyAuthCredentials'.
func (o ApiKeyAuthCredentialsResponseOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v ApiKeyAuthCredentialsResponse) string { return v.Kind }).(pulumi.StringOutput)
}

// Api properties.
type ApiProperties struct {
	// Interval in minutes for which the weather data for the api needs to be refreshed.
	ApiFreshnessTimeInMinutes *int `pulumi:"apiFreshnessTimeInMinutes"`
}

// ApiPropertiesInput is an input type that accepts ApiPropertiesArgs and ApiPropertiesOutput values.
// You can construct a concrete instance of `ApiPropertiesInput` via:
//
//	ApiPropertiesArgs{...}
type ApiPropertiesInput interface {
	pulumi.Input

	ToApiPropertiesOutput() ApiPropertiesOutput
	ToApiPropertiesOutputWithContext(context.Context) ApiPropertiesOutput
}

// Api properties.
type ApiPropertiesArgs struct {
	// Interval in minutes for which the weather data for the api needs to be refreshed.
	ApiFreshnessTimeInMinutes pulumi.IntPtrInput `pulumi:"apiFreshnessTimeInMinutes"`
}

func (ApiPropertiesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiProperties)(nil)).Elem()
}

func (i ApiPropertiesArgs) ToApiPropertiesOutput() ApiPropertiesOutput {
	return i.ToApiPropertiesOutputWithContext(context.Background())
}

func (i ApiPropertiesArgs) ToApiPropertiesOutputWithContext(ctx context.Context) ApiPropertiesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiPropertiesOutput)
}

// ApiPropertiesMapInput is an input type that accepts ApiPropertiesMap and ApiPropertiesMapOutput values.
// You can construct a concrete instance of `ApiPropertiesMapInput` via:
//
//	ApiPropertiesMap{ "key": ApiPropertiesArgs{...} }
type ApiPropertiesMapInput interface {
	pulumi.Input

	ToApiPropertiesMapOutput() ApiPropertiesMapOutput
	ToApiPropertiesMapOutputWithContext(context.Context) ApiPropertiesMapOutput
}

type ApiPropertiesMap map[string]ApiPropertiesInput

func (ApiPropertiesMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ApiProperties)(nil)).Elem()
}

func (i ApiPropertiesMap) ToApiPropertiesMapOutput() ApiPropertiesMapOutput {
	return i.ToApiPropertiesMapOutputWithContext(context.Background())
}

func (i ApiPropertiesMap) ToApiPropertiesMapOutputWithContext(ctx context.Context) ApiPropertiesMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiPropertiesMapOutput)
}

// Api properties.
type ApiPropertiesOutput struct{ *pulumi.OutputState }

func (ApiPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiProperties)(nil)).Elem()
}

func (o ApiPropertiesOutput) ToApiPropertiesOutput() ApiPropertiesOutput {
	return o
}

func (o ApiPropertiesOutput) ToApiPropertiesOutputWithContext(ctx context.Context) ApiPropertiesOutput {
	return o
}

// Interval in minutes for which the weather data for the api needs to be refreshed.
func (o ApiPropertiesOutput) ApiFreshnessTimeInMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ApiProperties) *int { return v.ApiFreshnessTimeInMinutes }).(pulumi.IntPtrOutput)
}

type ApiPropertiesMapOutput struct{ *pulumi.OutputState }

func (ApiPropertiesMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ApiProperties)(nil)).Elem()
}

func (o ApiPropertiesMapOutput) ToApiPropertiesMapOutput() ApiPropertiesMapOutput {
	return o
}

func (o ApiPropertiesMapOutput) ToApiPropertiesMapOutputWithContext(ctx context.Context) ApiPropertiesMapOutput {
	return o
}

func (o ApiPropertiesMapOutput) MapIndex(k pulumi.StringInput) ApiPropertiesOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ApiProperties {
		return vs[0].(map[string]ApiProperties)[vs[1].(string)]
	}).(ApiPropertiesOutput)
}

// Api properties.
type ApiPropertiesResponse struct {
	// Interval in minutes for which the weather data for the api needs to be refreshed.
	ApiFreshnessTimeInMinutes *int `pulumi:"apiFreshnessTimeInMinutes"`
}

// Api properties.
type ApiPropertiesResponseOutput struct{ *pulumi.OutputState }

func (ApiPropertiesResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiPropertiesResponse)(nil)).Elem()
}

func (o ApiPropertiesResponseOutput) ToApiPropertiesResponseOutput() ApiPropertiesResponseOutput {
	return o
}

func (o ApiPropertiesResponseOutput) ToApiPropertiesResponseOutputWithContext(ctx context.Context) ApiPropertiesResponseOutput {
	return o
}

// Interval in minutes for which the weather data for the api needs to be refreshed.
func (o ApiPropertiesResponseOutput) ApiFreshnessTimeInMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ApiPropertiesResponse) *int { return v.ApiFreshnessTimeInMinutes }).(pulumi.IntPtrOutput)
}

type ApiPropertiesResponseMapOutput struct{ *pulumi.OutputState }

func (ApiPropertiesResponseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ApiPropertiesResponse)(nil)).Elem()
}

func (o ApiPropertiesResponseMapOutput) ToApiPropertiesResponseMapOutput() ApiPropertiesResponseMapOutput {
	return o
}

func (o ApiPropertiesResponseMapOutput) ToApiPropertiesResponseMapOutputWithContext(ctx context.Context) ApiPropertiesResponseMapOutput {
	return o
}

func (o ApiPropertiesResponseMapOutput) MapIndex(k pulumi.StringInput) ApiPropertiesResponseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ApiPropertiesResponse {
		return vs[0].(map[string]ApiPropertiesResponse)[vs[1].(string)]
	}).(ApiPropertiesResponseOutput)
}

// DataConnector Properties.
type DataConnectorProperties struct {
	// AuthCredentials abstract base class for Auth Purpose.
	Credentials interface{} `pulumi:"credentials"`
}

// DataConnectorPropertiesInput is an input type that accepts DataConnectorPropertiesArgs and DataConnectorPropertiesOutput values.
// You can construct a concrete instance of `DataConnectorPropertiesInput` via:
//
//	DataConnectorPropertiesArgs{...}
type DataConnectorPropertiesInput interface {
	pulumi.Input

	ToDataConnectorPropertiesOutput() DataConnectorPropertiesOutput
	ToDataConnectorPropertiesOutputWithContext(context.Context) DataConnectorPropertiesOutput
}

// DataConnector Properties.
type DataConnectorPropertiesArgs struct {
	// AuthCredentials abstract base class for Auth Purpose.
	Credentials pulumi.Input `pulumi:"credentials"`
}

func (DataConnectorPropertiesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataConnectorProperties)(nil)).Elem()
}

func (i DataConnectorPropertiesArgs) ToDataConnectorPropertiesOutput() DataConnectorPropertiesOutput {
	return i.ToDataConnectorPropertiesOutputWithContext(context.Background())
}

func (i DataConnectorPropertiesArgs) ToDataConnectorPropertiesOutputWithContext(ctx context.Context) DataConnectorPropertiesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataConnectorPropertiesOutput)
}

// DataConnector Properties.
type DataConnectorPropertiesOutput struct{ *pulumi.OutputState }

func (DataConnectorPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataConnectorProperties)(nil)).Elem()
}

func (o DataConnectorPropertiesOutput) ToDataConnectorPropertiesOutput() DataConnectorPropertiesOutput {
	return o
}

func (o DataConnectorPropertiesOutput) ToDataConnectorPropertiesOutputWithContext(ctx context.Context) DataConnectorPropertiesOutput {
	return o
}

// AuthCredentials abstract base class for Auth Purpose.
func (o DataConnectorPropertiesOutput) Credentials() pulumi.AnyOutput {
	return o.ApplyT(func(v DataConnectorProperties) interface{} { return v.Credentials }).(pulumi.AnyOutput)
}

// DataConnector Properties.
type DataConnectorPropertiesResponse struct {
	// AuthCredentials abstract base class for Auth Purpose.
	Credentials interface{} `pulumi:"credentials"`
}

// DataConnector Properties.
type DataConnectorPropertiesResponseOutput struct{ *pulumi.OutputState }

func (DataConnectorPropertiesResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataConnectorPropertiesResponse)(nil)).Elem()
}

func (o DataConnectorPropertiesResponseOutput) ToDataConnectorPropertiesResponseOutput() DataConnectorPropertiesResponseOutput {
	return o
}

func (o DataConnectorPropertiesResponseOutput) ToDataConnectorPropertiesResponseOutputWithContext(ctx context.Context) DataConnectorPropertiesResponseOutput {
	return o
}

// AuthCredentials abstract base class for Auth Purpose.
func (o DataConnectorPropertiesResponseOutput) Credentials() pulumi.AnyOutput {
	return o.ApplyT(func(v DataConnectorPropertiesResponse) interface{} { return v.Credentials }).(pulumi.AnyOutput)
}

// Properties of the key vault.
type KeyVaultProperties struct {
	// Name of Key Vault key.
	KeyName string `pulumi:"keyName"`
	// Uri of the key vault.
	KeyVaultUri string `pulumi:"keyVaultUri"`
	// Version of Key Vault key.
	KeyVersion string `pulumi:"keyVersion"`
}

// KeyVaultPropertiesInput is an input type that accepts KeyVaultPropertiesArgs and KeyVaultPropertiesOutput values.
// You can construct a concrete instance of `KeyVaultPropertiesInput` via:
//
//	KeyVaultPropertiesArgs{...}
type KeyVaultPropertiesInput interface {
	pulumi.Input

	ToKeyVaultPropertiesOutput() KeyVaultPropertiesOutput
	ToKeyVaultPropertiesOutputWithContext(context.Context) KeyVaultPropertiesOutput
}

// Properties of the key vault.
type KeyVaultPropertiesArgs struct {
	// Name of Key Vault key.
	KeyName pulumi.StringInput `pulumi:"keyName"`
	// Uri of the key vault.
	KeyVaultUri pulumi.StringInput `pulumi:"keyVaultUri"`
	// Version of Key Vault key.
	KeyVersion pulumi.StringInput `pulumi:"keyVersion"`
}

func (KeyVaultPropertiesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KeyVaultProperties)(nil)).Elem()
}

func (i KeyVaultPropertiesArgs) ToKeyVaultPropertiesOutput() KeyVaultPropertiesOutput {
	return i.ToKeyVaultPropertiesOutputWithContext(context.Background())
}

func (i KeyVaultPropertiesArgs) ToKeyVaultPropertiesOutputWithContext(ctx context.Context) KeyVaultPropertiesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyVaultPropertiesOutput)
}

// Properties of the key vault.
type KeyVaultPropertiesOutput struct{ *pulumi.OutputState }

func (KeyVaultPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KeyVaultProperties)(nil)).Elem()
}

func (o KeyVaultPropertiesOutput) ToKeyVaultPropertiesOutput() KeyVaultPropertiesOutput {
	return o
}

func (o KeyVaultPropertiesOutput) ToKeyVaultPropertiesOutputWithContext(ctx context.Context) KeyVaultPropertiesOutput {
	return o
}

// Name of Key Vault key.
func (o KeyVaultPropertiesOutput) KeyName() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultProperties) string { return v.KeyName }).(pulumi.StringOutput)
}

// Uri of the key vault.
func (o KeyVaultPropertiesOutput) KeyVaultUri() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultProperties) string { return v.KeyVaultUri }).(pulumi.StringOutput)
}

// Version of Key Vault key.
func (o KeyVaultPropertiesOutput) KeyVersion() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultProperties) string { return v.KeyVersion }).(pulumi.StringOutput)
}

// Properties of the key vault.
type KeyVaultPropertiesResponse struct {
	// Name of Key Vault key.
	KeyName string `pulumi:"keyName"`
	// Uri of the key vault.
	KeyVaultUri string `pulumi:"keyVaultUri"`
	// Version of Key Vault key.
	KeyVersion string `pulumi:"keyVersion"`
}

// Properties of the key vault.
type KeyVaultPropertiesResponseOutput struct{ *pulumi.OutputState }

func (KeyVaultPropertiesResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KeyVaultPropertiesResponse)(nil)).Elem()
}

func (o KeyVaultPropertiesResponseOutput) ToKeyVaultPropertiesResponseOutput() KeyVaultPropertiesResponseOutput {
	return o
}

func (o KeyVaultPropertiesResponseOutput) ToKeyVaultPropertiesResponseOutputWithContext(ctx context.Context) KeyVaultPropertiesResponseOutput {
	return o
}

// Name of Key Vault key.
func (o KeyVaultPropertiesResponseOutput) KeyName() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultPropertiesResponse) string { return v.KeyName }).(pulumi.StringOutput)
}

// Uri of the key vault.
func (o KeyVaultPropertiesResponseOutput) KeyVaultUri() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultPropertiesResponse) string { return v.KeyVaultUri }).(pulumi.StringOutput)
}

// Version of Key Vault key.
func (o KeyVaultPropertiesResponseOutput) KeyVersion() pulumi.StringOutput {
	return o.ApplyT(func(v KeyVaultPropertiesResponse) string { return v.KeyVersion }).(pulumi.StringOutput)
}

// OAuthClientCredentials for clientId clientSecret auth.
type OAuthClientCredentials struct {
	// ClientId associated with the provider.
	ClientId string `pulumi:"clientId"`
	// Properties of the key vault.
	ClientSecret KeyVaultProperties `pulumi:"clientSecret"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'OAuthClientCredentials'.
	Kind string `pulumi:"kind"`
}

// OAuthClientCredentialsInput is an input type that accepts OAuthClientCredentialsArgs and OAuthClientCredentialsOutput values.
// You can construct a concrete instance of `OAuthClientCredentialsInput` via:
//
//	OAuthClientCredentialsArgs{...}
type OAuthClientCredentialsInput interface {
	pulumi.Input

	ToOAuthClientCredentialsOutput() OAuthClientCredentialsOutput
	ToOAuthClientCredentialsOutputWithContext(context.Context) OAuthClientCredentialsOutput
}

// OAuthClientCredentials for clientId clientSecret auth.
type OAuthClientCredentialsArgs struct {
	// ClientId associated with the provider.
	ClientId pulumi.StringInput `pulumi:"clientId"`
	// Properties of the key vault.
	ClientSecret KeyVaultPropertiesInput `pulumi:"clientSecret"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'OAuthClientCredentials'.
	Kind pulumi.StringInput `pulumi:"kind"`
}

func (OAuthClientCredentialsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*OAuthClientCredentials)(nil)).Elem()
}

func (i OAuthClientCredentialsArgs) ToOAuthClientCredentialsOutput() OAuthClientCredentialsOutput {
	return i.ToOAuthClientCredentialsOutputWithContext(context.Background())
}

func (i OAuthClientCredentialsArgs) ToOAuthClientCredentialsOutputWithContext(ctx context.Context) OAuthClientCredentialsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OAuthClientCredentialsOutput)
}

// OAuthClientCredentials for clientId clientSecret auth.
type OAuthClientCredentialsOutput struct{ *pulumi.OutputState }

func (OAuthClientCredentialsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*OAuthClientCredentials)(nil)).Elem()
}

func (o OAuthClientCredentialsOutput) ToOAuthClientCredentialsOutput() OAuthClientCredentialsOutput {
	return o
}

func (o OAuthClientCredentialsOutput) ToOAuthClientCredentialsOutputWithContext(ctx context.Context) OAuthClientCredentialsOutput {
	return o
}

// ClientId associated with the provider.
func (o OAuthClientCredentialsOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v OAuthClientCredentials) string { return v.ClientId }).(pulumi.StringOutput)
}

// Properties of the key vault.
func (o OAuthClientCredentialsOutput) ClientSecret() KeyVaultPropertiesOutput {
	return o.ApplyT(func(v OAuthClientCredentials) KeyVaultProperties { return v.ClientSecret }).(KeyVaultPropertiesOutput)
}

// Enum for different types of AuthCredentials supported.
// Expected value is 'OAuthClientCredentials'.
func (o OAuthClientCredentialsOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v OAuthClientCredentials) string { return v.Kind }).(pulumi.StringOutput)
}

// OAuthClientCredentials for clientId clientSecret auth.
type OAuthClientCredentialsResponse struct {
	// ClientId associated with the provider.
	ClientId string `pulumi:"clientId"`
	// Properties of the key vault.
	ClientSecret KeyVaultPropertiesResponse `pulumi:"clientSecret"`
	// Enum for different types of AuthCredentials supported.
	// Expected value is 'OAuthClientCredentials'.
	Kind string `pulumi:"kind"`
}

// OAuthClientCredentials for clientId clientSecret auth.
type OAuthClientCredentialsResponseOutput struct{ *pulumi.OutputState }

func (OAuthClientCredentialsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*OAuthClientCredentialsResponse)(nil)).Elem()
}

func (o OAuthClientCredentialsResponseOutput) ToOAuthClientCredentialsResponseOutput() OAuthClientCredentialsResponseOutput {
	return o
}

func (o OAuthClientCredentialsResponseOutput) ToOAuthClientCredentialsResponseOutputWithContext(ctx context.Context) OAuthClientCredentialsResponseOutput {
	return o
}

// ClientId associated with the provider.
func (o OAuthClientCredentialsResponseOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v OAuthClientCredentialsResponse) string { return v.ClientId }).(pulumi.StringOutput)
}

// Properties of the key vault.
func (o OAuthClientCredentialsResponseOutput) ClientSecret() KeyVaultPropertiesResponseOutput {
	return o.ApplyT(func(v OAuthClientCredentialsResponse) KeyVaultPropertiesResponse { return v.ClientSecret }).(KeyVaultPropertiesResponseOutput)
}

// Enum for different types of AuthCredentials supported.
// Expected value is 'OAuthClientCredentials'.
func (o OAuthClientCredentialsResponseOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v OAuthClientCredentialsResponse) string { return v.Kind }).(pulumi.StringOutput)
}

// Sensor integration request model.
type SensorIntegration struct {
	// Sensor integration enable state.
	Enabled *string `pulumi:"enabled"`
}

// SensorIntegrationInput is an input type that accepts SensorIntegrationArgs and SensorIntegrationOutput values.
// You can construct a concrete instance of `SensorIntegrationInput` via:
//
//	SensorIntegrationArgs{...}
type SensorIntegrationInput interface {
	pulumi.Input

	ToSensorIntegrationOutput() SensorIntegrationOutput
	ToSensorIntegrationOutputWithContext(context.Context) SensorIntegrationOutput
}

// Sensor integration request model.
type SensorIntegrationArgs struct {
	// Sensor integration enable state.
	Enabled pulumi.StringPtrInput `pulumi:"enabled"`
}

func (SensorIntegrationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SensorIntegration)(nil)).Elem()
}

func (i SensorIntegrationArgs) ToSensorIntegrationOutput() SensorIntegrationOutput {
	return i.ToSensorIntegrationOutputWithContext(context.Background())
}

func (i SensorIntegrationArgs) ToSensorIntegrationOutputWithContext(ctx context.Context) SensorIntegrationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SensorIntegrationOutput)
}

func (i SensorIntegrationArgs) ToSensorIntegrationPtrOutput() SensorIntegrationPtrOutput {
	return i.ToSensorIntegrationPtrOutputWithContext(context.Background())
}

func (i SensorIntegrationArgs) ToSensorIntegrationPtrOutputWithContext(ctx context.Context) SensorIntegrationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SensorIntegrationOutput).ToSensorIntegrationPtrOutputWithContext(ctx)
}

// SensorIntegrationPtrInput is an input type that accepts SensorIntegrationArgs, SensorIntegrationPtr and SensorIntegrationPtrOutput values.
// You can construct a concrete instance of `SensorIntegrationPtrInput` via:
//
//	        SensorIntegrationArgs{...}
//
//	or:
//
//	        nil
type SensorIntegrationPtrInput interface {
	pulumi.Input

	ToSensorIntegrationPtrOutput() SensorIntegrationPtrOutput
	ToSensorIntegrationPtrOutputWithContext(context.Context) SensorIntegrationPtrOutput
}

type sensorIntegrationPtrType SensorIntegrationArgs

func SensorIntegrationPtr(v *SensorIntegrationArgs) SensorIntegrationPtrInput {
	return (*sensorIntegrationPtrType)(v)
}

func (*sensorIntegrationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SensorIntegration)(nil)).Elem()
}

func (i *sensorIntegrationPtrType) ToSensorIntegrationPtrOutput() SensorIntegrationPtrOutput {
	return i.ToSensorIntegrationPtrOutputWithContext(context.Background())
}

func (i *sensorIntegrationPtrType) ToSensorIntegrationPtrOutputWithContext(ctx context.Context) SensorIntegrationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SensorIntegrationPtrOutput)
}

// Sensor integration request model.
type SensorIntegrationOutput struct{ *pulumi.OutputState }

func (SensorIntegrationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SensorIntegration)(nil)).Elem()
}

func (o SensorIntegrationOutput) ToSensorIntegrationOutput() SensorIntegrationOutput {
	return o
}

func (o SensorIntegrationOutput) ToSensorIntegrationOutputWithContext(ctx context.Context) SensorIntegrationOutput {
	return o
}

func (o SensorIntegrationOutput) ToSensorIntegrationPtrOutput() SensorIntegrationPtrOutput {
	return o.ToSensorIntegrationPtrOutputWithContext(context.Background())
}

func (o SensorIntegrationOutput) ToSensorIntegrationPtrOutputWithContext(ctx context.Context) SensorIntegrationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SensorIntegration) *SensorIntegration {
		return &v
	}).(SensorIntegrationPtrOutput)
}

// Sensor integration enable state.
func (o SensorIntegrationOutput) Enabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SensorIntegration) *string { return v.Enabled }).(pulumi.StringPtrOutput)
}

type SensorIntegrationPtrOutput struct{ *pulumi.OutputState }

func (SensorIntegrationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SensorIntegration)(nil)).Elem()
}

func (o SensorIntegrationPtrOutput) ToSensorIntegrationPtrOutput() SensorIntegrationPtrOutput {
	return o
}

func (o SensorIntegrationPtrOutput) ToSensorIntegrationPtrOutputWithContext(ctx context.Context) SensorIntegrationPtrOutput {
	return o
}

func (o SensorIntegrationPtrOutput) Elem() SensorIntegrationOutput {
	return o.ApplyT(func(v *SensorIntegration) SensorIntegration {
		if v != nil {
			return *v
		}
		var ret SensorIntegration
		return ret
	}).(SensorIntegrationOutput)
}

// Sensor integration enable state.
func (o SensorIntegrationPtrOutput) Enabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SensorIntegration) *string {
		if v == nil {
			return nil
		}
		return v.Enabled
	}).(pulumi.StringPtrOutput)
}

// Sensor integration request model.
type SensorIntegrationResponse struct {
	// Sensor integration enable state.
	Enabled *string `pulumi:"enabled"`
	// Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
	ProvisioningInfo *commontypesv4.ErrorResponseResponse `pulumi:"provisioningInfo"`
	// Sensor integration instance provisioning state.
	ProvisioningState string `pulumi:"provisioningState"`
}

// Sensor integration request model.
type SensorIntegrationResponseOutput struct{ *pulumi.OutputState }

func (SensorIntegrationResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SensorIntegrationResponse)(nil)).Elem()
}

func (o SensorIntegrationResponseOutput) ToSensorIntegrationResponseOutput() SensorIntegrationResponseOutput {
	return o
}

func (o SensorIntegrationResponseOutput) ToSensorIntegrationResponseOutputWithContext(ctx context.Context) SensorIntegrationResponseOutput {
	return o
}

// Sensor integration enable state.
func (o SensorIntegrationResponseOutput) Enabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SensorIntegrationResponse) *string { return v.Enabled }).(pulumi.StringPtrOutput)
}

// Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
func (o SensorIntegrationResponseOutput) ProvisioningInfo() commontypesv4.ErrorResponseResponsePtrOutput {
	return o.ApplyT(func(v SensorIntegrationResponse) *commontypesv4.ErrorResponseResponse { return v.ProvisioningInfo }).(commontypesv4.ErrorResponseResponsePtrOutput)
}

// Sensor integration instance provisioning state.
func (o SensorIntegrationResponseOutput) ProvisioningState() pulumi.StringOutput {
	return o.ApplyT(func(v SensorIntegrationResponse) string { return v.ProvisioningState }).(pulumi.StringOutput)
}

type SensorIntegrationResponsePtrOutput struct{ *pulumi.OutputState }

func (SensorIntegrationResponsePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SensorIntegrationResponse)(nil)).Elem()
}

func (o SensorIntegrationResponsePtrOutput) ToSensorIntegrationResponsePtrOutput() SensorIntegrationResponsePtrOutput {
	return o
}

func (o SensorIntegrationResponsePtrOutput) ToSensorIntegrationResponsePtrOutputWithContext(ctx context.Context) SensorIntegrationResponsePtrOutput {
	return o
}

func (o SensorIntegrationResponsePtrOutput) Elem() SensorIntegrationResponseOutput {
	return o.ApplyT(func(v *SensorIntegrationResponse) SensorIntegrationResponse {
		if v != nil {
			return *v
		}
		var ret SensorIntegrationResponse
		return ret
	}).(SensorIntegrationResponseOutput)
}

// Sensor integration enable state.
func (o SensorIntegrationResponsePtrOutput) Enabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SensorIntegrationResponse) *string {
		if v == nil {
			return nil
		}
		return v.Enabled
	}).(pulumi.StringPtrOutput)
}

// Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
func (o SensorIntegrationResponsePtrOutput) ProvisioningInfo() commontypesv4.ErrorResponseResponsePtrOutput {
	return o.ApplyT(func(v *SensorIntegrationResponse) *commontypesv4.ErrorResponseResponse {
		if v == nil {
			return nil
		}
		return v.ProvisioningInfo
	}).(commontypesv4.ErrorResponseResponsePtrOutput)
}

// Sensor integration instance provisioning state.
func (o SensorIntegrationResponsePtrOutput) ProvisioningState() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SensorIntegrationResponse) *string {
		if v == nil {
			return nil
		}
		return &v.ProvisioningState
	}).(pulumi.StringPtrOutput)
}

// Solution resource properties.
type SolutionProperties struct {
	// SaaS application Marketplace Publisher Id.
	MarketplacePublisherId string `pulumi:"marketplacePublisherId"`
	// SaaS application Offer Id.
	OfferId string `pulumi:"offerId"`
	// SaaS application Plan Id.
	PlanId string `pulumi:"planId"`
	// Role Assignment Id.
	RoleAssignmentId *string `pulumi:"roleAssignmentId"`
	// SaaS subscriptionId of the installed SaaS application.
	SaasSubscriptionId string `pulumi:"saasSubscriptionId"`
	// SaaS subscription name of the installed SaaS application.
	SaasSubscriptionName string `pulumi:"saasSubscriptionName"`
	// SaaS application Term Id.
	TermId string `pulumi:"termId"`
}

// SolutionPropertiesInput is an input type that accepts SolutionPropertiesArgs and SolutionPropertiesOutput values.
// You can construct a concrete instance of `SolutionPropertiesInput` via:
//
//	SolutionPropertiesArgs{...}
type SolutionPropertiesInput interface {
	pulumi.Input

	ToSolutionPropertiesOutput() SolutionPropertiesOutput
	ToSolutionPropertiesOutputWithContext(context.Context) SolutionPropertiesOutput
}

// Solution resource properties.
type SolutionPropertiesArgs struct {
	// SaaS application Marketplace Publisher Id.
	MarketplacePublisherId pulumi.StringInput `pulumi:"marketplacePublisherId"`
	// SaaS application Offer Id.
	OfferId pulumi.StringInput `pulumi:"offerId"`
	// SaaS application Plan Id.
	PlanId pulumi.StringInput `pulumi:"planId"`
	// Role Assignment Id.
	RoleAssignmentId pulumi.StringPtrInput `pulumi:"roleAssignmentId"`
	// SaaS subscriptionId of the installed SaaS application.
	SaasSubscriptionId pulumi.StringInput `pulumi:"saasSubscriptionId"`
	// SaaS subscription name of the installed SaaS application.
	SaasSubscriptionName pulumi.StringInput `pulumi:"saasSubscriptionName"`
	// SaaS application Term Id.
	TermId pulumi.StringInput `pulumi:"termId"`
}

func (SolutionPropertiesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SolutionProperties)(nil)).Elem()
}

func (i SolutionPropertiesArgs) ToSolutionPropertiesOutput() SolutionPropertiesOutput {
	return i.ToSolutionPropertiesOutputWithContext(context.Background())
}

func (i SolutionPropertiesArgs) ToSolutionPropertiesOutputWithContext(ctx context.Context) SolutionPropertiesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SolutionPropertiesOutput)
}

func (i SolutionPropertiesArgs) ToSolutionPropertiesPtrOutput() SolutionPropertiesPtrOutput {
	return i.ToSolutionPropertiesPtrOutputWithContext(context.Background())
}

func (i SolutionPropertiesArgs) ToSolutionPropertiesPtrOutputWithContext(ctx context.Context) SolutionPropertiesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SolutionPropertiesOutput).ToSolutionPropertiesPtrOutputWithContext(ctx)
}

// SolutionPropertiesPtrInput is an input type that accepts SolutionPropertiesArgs, SolutionPropertiesPtr and SolutionPropertiesPtrOutput values.
// You can construct a concrete instance of `SolutionPropertiesPtrInput` via:
//
//	        SolutionPropertiesArgs{...}
//
//	or:
//
//	        nil
type SolutionPropertiesPtrInput interface {
	pulumi.Input

	ToSolutionPropertiesPtrOutput() SolutionPropertiesPtrOutput
	ToSolutionPropertiesPtrOutputWithContext(context.Context) SolutionPropertiesPtrOutput
}

type solutionPropertiesPtrType SolutionPropertiesArgs

func SolutionPropertiesPtr(v *SolutionPropertiesArgs) SolutionPropertiesPtrInput {
	return (*solutionPropertiesPtrType)(v)
}

func (*solutionPropertiesPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SolutionProperties)(nil)).Elem()
}

func (i *solutionPropertiesPtrType) ToSolutionPropertiesPtrOutput() SolutionPropertiesPtrOutput {
	return i.ToSolutionPropertiesPtrOutputWithContext(context.Background())
}

func (i *solutionPropertiesPtrType) ToSolutionPropertiesPtrOutputWithContext(ctx context.Context) SolutionPropertiesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SolutionPropertiesPtrOutput)
}

// Solution resource properties.
type SolutionPropertiesOutput struct{ *pulumi.OutputState }

func (SolutionPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SolutionProperties)(nil)).Elem()
}

func (o SolutionPropertiesOutput) ToSolutionPropertiesOutput() SolutionPropertiesOutput {
	return o
}

func (o SolutionPropertiesOutput) ToSolutionPropertiesOutputWithContext(ctx context.Context) SolutionPropertiesOutput {
	return o
}

func (o SolutionPropertiesOutput) ToSolutionPropertiesPtrOutput() SolutionPropertiesPtrOutput {
	return o.ToSolutionPropertiesPtrOutputWithContext(context.Background())
}

func (o SolutionPropertiesOutput) ToSolutionPropertiesPtrOutputWithContext(ctx context.Context) SolutionPropertiesPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SolutionProperties) *SolutionProperties {
		return &v
	}).(SolutionPropertiesPtrOutput)
}

// SaaS application Marketplace Publisher Id.
func (o SolutionPropertiesOutput) MarketplacePublisherId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.MarketplacePublisherId }).(pulumi.StringOutput)
}

// SaaS application Offer Id.
func (o SolutionPropertiesOutput) OfferId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.OfferId }).(pulumi.StringOutput)
}

// SaaS application Plan Id.
func (o SolutionPropertiesOutput) PlanId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.PlanId }).(pulumi.StringOutput)
}

// Role Assignment Id.
func (o SolutionPropertiesOutput) RoleAssignmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SolutionProperties) *string { return v.RoleAssignmentId }).(pulumi.StringPtrOutput)
}

// SaaS subscriptionId of the installed SaaS application.
func (o SolutionPropertiesOutput) SaasSubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.SaasSubscriptionId }).(pulumi.StringOutput)
}

// SaaS subscription name of the installed SaaS application.
func (o SolutionPropertiesOutput) SaasSubscriptionName() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.SaasSubscriptionName }).(pulumi.StringOutput)
}

// SaaS application Term Id.
func (o SolutionPropertiesOutput) TermId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionProperties) string { return v.TermId }).(pulumi.StringOutput)
}

type SolutionPropertiesPtrOutput struct{ *pulumi.OutputState }

func (SolutionPropertiesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SolutionProperties)(nil)).Elem()
}

func (o SolutionPropertiesPtrOutput) ToSolutionPropertiesPtrOutput() SolutionPropertiesPtrOutput {
	return o
}

func (o SolutionPropertiesPtrOutput) ToSolutionPropertiesPtrOutputWithContext(ctx context.Context) SolutionPropertiesPtrOutput {
	return o
}

func (o SolutionPropertiesPtrOutput) Elem() SolutionPropertiesOutput {
	return o.ApplyT(func(v *SolutionProperties) SolutionProperties {
		if v != nil {
			return *v
		}
		var ret SolutionProperties
		return ret
	}).(SolutionPropertiesOutput)
}

// SaaS application Marketplace Publisher Id.
func (o SolutionPropertiesPtrOutput) MarketplacePublisherId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.MarketplacePublisherId
	}).(pulumi.StringPtrOutput)
}

// SaaS application Offer Id.
func (o SolutionPropertiesPtrOutput) OfferId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.OfferId
	}).(pulumi.StringPtrOutput)
}

// SaaS application Plan Id.
func (o SolutionPropertiesPtrOutput) PlanId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.PlanId
	}).(pulumi.StringPtrOutput)
}

// Role Assignment Id.
func (o SolutionPropertiesPtrOutput) RoleAssignmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return v.RoleAssignmentId
	}).(pulumi.StringPtrOutput)
}

// SaaS subscriptionId of the installed SaaS application.
func (o SolutionPropertiesPtrOutput) SaasSubscriptionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.SaasSubscriptionId
	}).(pulumi.StringPtrOutput)
}

// SaaS subscription name of the installed SaaS application.
func (o SolutionPropertiesPtrOutput) SaasSubscriptionName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.SaasSubscriptionName
	}).(pulumi.StringPtrOutput)
}

// SaaS application Term Id.
func (o SolutionPropertiesPtrOutput) TermId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SolutionProperties) *string {
		if v == nil {
			return nil
		}
		return &v.TermId
	}).(pulumi.StringPtrOutput)
}

// Solution resource properties.
type SolutionPropertiesResponse struct {
	// SaaS application Marketplace Publisher Id.
	MarketplacePublisherId string `pulumi:"marketplacePublisherId"`
	// SaaS application Offer Id.
	OfferId string `pulumi:"offerId"`
	// Partner Id of the Solution.
	PartnerId string `pulumi:"partnerId"`
	// SaaS application Plan Id.
	PlanId string `pulumi:"planId"`
	// Role Assignment Id.
	RoleAssignmentId *string `pulumi:"roleAssignmentId"`
	// SaaS subscriptionId of the installed SaaS application.
	SaasSubscriptionId string `pulumi:"saasSubscriptionId"`
	// SaaS subscription name of the installed SaaS application.
	SaasSubscriptionName string `pulumi:"saasSubscriptionName"`
	// SaaS application Term Id.
	TermId string `pulumi:"termId"`
}

// Solution resource properties.
type SolutionPropertiesResponseOutput struct{ *pulumi.OutputState }

func (SolutionPropertiesResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SolutionPropertiesResponse)(nil)).Elem()
}

func (o SolutionPropertiesResponseOutput) ToSolutionPropertiesResponseOutput() SolutionPropertiesResponseOutput {
	return o
}

func (o SolutionPropertiesResponseOutput) ToSolutionPropertiesResponseOutputWithContext(ctx context.Context) SolutionPropertiesResponseOutput {
	return o
}

// SaaS application Marketplace Publisher Id.
func (o SolutionPropertiesResponseOutput) MarketplacePublisherId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.MarketplacePublisherId }).(pulumi.StringOutput)
}

// SaaS application Offer Id.
func (o SolutionPropertiesResponseOutput) OfferId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.OfferId }).(pulumi.StringOutput)
}

// Partner Id of the Solution.
func (o SolutionPropertiesResponseOutput) PartnerId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.PartnerId }).(pulumi.StringOutput)
}

// SaaS application Plan Id.
func (o SolutionPropertiesResponseOutput) PlanId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.PlanId }).(pulumi.StringOutput)
}

// Role Assignment Id.
func (o SolutionPropertiesResponseOutput) RoleAssignmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) *string { return v.RoleAssignmentId }).(pulumi.StringPtrOutput)
}

// SaaS subscriptionId of the installed SaaS application.
func (o SolutionPropertiesResponseOutput) SaasSubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.SaasSubscriptionId }).(pulumi.StringOutput)
}

// SaaS subscription name of the installed SaaS application.
func (o SolutionPropertiesResponseOutput) SaasSubscriptionName() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.SaasSubscriptionName }).(pulumi.StringOutput)
}

// SaaS application Term Id.
func (o SolutionPropertiesResponseOutput) TermId() pulumi.StringOutput {
	return o.ApplyT(func(v SolutionPropertiesResponse) string { return v.TermId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ApiKeyAuthCredentialsOutput{})
	pulumi.RegisterOutputType(ApiKeyAuthCredentialsResponseOutput{})
	pulumi.RegisterOutputType(ApiPropertiesOutput{})
	pulumi.RegisterOutputType(ApiPropertiesMapOutput{})
	pulumi.RegisterOutputType(ApiPropertiesResponseOutput{})
	pulumi.RegisterOutputType(ApiPropertiesResponseMapOutput{})
	pulumi.RegisterOutputType(DataConnectorPropertiesOutput{})
	pulumi.RegisterOutputType(DataConnectorPropertiesResponseOutput{})
	pulumi.RegisterOutputType(KeyVaultPropertiesOutput{})
	pulumi.RegisterOutputType(KeyVaultPropertiesResponseOutput{})
	pulumi.RegisterOutputType(OAuthClientCredentialsOutput{})
	pulumi.RegisterOutputType(OAuthClientCredentialsResponseOutput{})
	pulumi.RegisterOutputType(SensorIntegrationOutput{})
	pulumi.RegisterOutputType(SensorIntegrationPtrOutput{})
	pulumi.RegisterOutputType(SensorIntegrationResponseOutput{})
	pulumi.RegisterOutputType(SensorIntegrationResponsePtrOutput{})
	pulumi.RegisterOutputType(SolutionPropertiesOutput{})
	pulumi.RegisterOutputType(SolutionPropertiesPtrOutput{})
	pulumi.RegisterOutputType(SolutionPropertiesResponseOutput{})
}
