// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20161101

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// BitLocker recovery key or password to the specified drive
type DriveBitLockerKeyResponse struct {
	// BitLocker recovery key or password
	BitLockerKey *string `pulumi:"bitLockerKey"`
	// Drive ID
	DriveId *string `pulumi:"driveId"`
}

// BitLocker recovery key or password to the specified drive
type DriveBitLockerKeyResponseOutput struct{ *pulumi.OutputState }

func (DriveBitLockerKeyResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DriveBitLockerKeyResponse)(nil)).Elem()
}

func (o DriveBitLockerKeyResponseOutput) ToDriveBitLockerKeyResponseOutput() DriveBitLockerKeyResponseOutput {
	return o
}

func (o DriveBitLockerKeyResponseOutput) ToDriveBitLockerKeyResponseOutputWithContext(ctx context.Context) DriveBitLockerKeyResponseOutput {
	return o
}

// BitLocker recovery key or password
func (o DriveBitLockerKeyResponseOutput) BitLockerKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DriveBitLockerKeyResponse) *string { return v.BitLockerKey }).(pulumi.StringPtrOutput)
}

// Drive ID
func (o DriveBitLockerKeyResponseOutput) DriveId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DriveBitLockerKeyResponse) *string { return v.DriveId }).(pulumi.StringPtrOutput)
}

type DriveBitLockerKeyResponseArrayOutput struct{ *pulumi.OutputState }

func (DriveBitLockerKeyResponseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DriveBitLockerKeyResponse)(nil)).Elem()
}

func (o DriveBitLockerKeyResponseArrayOutput) ToDriveBitLockerKeyResponseArrayOutput() DriveBitLockerKeyResponseArrayOutput {
	return o
}

func (o DriveBitLockerKeyResponseArrayOutput) ToDriveBitLockerKeyResponseArrayOutputWithContext(ctx context.Context) DriveBitLockerKeyResponseArrayOutput {
	return o
}

func (o DriveBitLockerKeyResponseArrayOutput) Index(i pulumi.IntInput) DriveBitLockerKeyResponseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DriveBitLockerKeyResponse {
		return vs[0].([]DriveBitLockerKeyResponse)[vs[1].(int)]
	}).(DriveBitLockerKeyResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(DriveBitLockerKeyResponseOutput{})
	pulumi.RegisterOutputType(DriveBitLockerKeyResponseArrayOutput{})
}
