// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package migrate

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get the URL for downloading the business case in a report format.
// Azure REST API version: 2024-01-01-preview.
func GetAssessmentProjectsBusinessCaseOperationReportDownloadUrl(ctx *pulumi.Context, args *GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlArgs, opts ...pulumi.InvokeOption) (*GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult
	err := ctx.Invoke("azure-native:migrate:getAssessmentProjectsBusinessCaseOperationReportDownloadUrl", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlArgs struct {
	// Business case ARM name
	BusinessCaseName string `pulumi:"businessCaseName"`
	// Assessment Project Name
	ProjectName string `pulumi:"projectName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// Download URL for assessment report.
type GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult struct {
	// Hyperlink to download report.
	BusinessCaseReportUrl string `pulumi:"businessCaseReportUrl"`
	// Expiry date of download url.
	ExpirationTime string `pulumi:"expirationTime"`
}

func GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlOutput(ctx *pulumi.Context, args GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlOutputArgs, opts ...pulumi.InvokeOption) GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput, error) {
			args := v.(GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:migrate:getAssessmentProjectsBusinessCaseOperationReportDownloadUrl", args, GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput{}, options).(GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput), nil
		}).(GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput)
}

type GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlOutputArgs struct {
	// Business case ARM name
	BusinessCaseName pulumi.StringInput `pulumi:"businessCaseName"`
	// Assessment Project Name
	ProjectName pulumi.StringInput `pulumi:"projectName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlArgs)(nil)).Elem()
}

// Download URL for assessment report.
type GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput struct{ *pulumi.OutputState }

func (GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult)(nil)).Elem()
}

func (o GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput) ToGetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput() GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput {
	return o
}

func (o GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput) ToGetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutputWithContext(ctx context.Context) GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput {
	return o
}

// Hyperlink to download report.
func (o GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput) BusinessCaseReportUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult) string {
		return v.BusinessCaseReportUrl
	}).(pulumi.StringOutput)
}

// Expiry date of download url.
func (o GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput) ExpirationTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResult) string {
		return v.ExpirationTime
	}).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAssessmentProjectsBusinessCaseOperationReportDownloadUrlResultOutput{})
}
