// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package appplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get the Monitoring Setting and its properties.
//
// Uses Azure REST API version 2024-01-01-preview.
//
// Other available API versions: 2023-05-01-preview, 2023-07-01-preview, 2023-09-01-preview, 2023-11-01-preview, 2023-12-01, 2024-05-01-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native appplatform [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
func LookupMonitoringSetting(ctx *pulumi.Context, args *LookupMonitoringSettingArgs, opts ...pulumi.InvokeOption) (*LookupMonitoringSettingResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupMonitoringSettingResult
	err := ctx.Invoke("azure-native:appplatform:getMonitoringSetting", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupMonitoringSettingArgs struct {
	// The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The name of the Service resource.
	ServiceName string `pulumi:"serviceName"`
}

// Monitoring Setting resource
type LookupMonitoringSettingResult struct {
	// The Azure API version of the resource.
	AzureApiVersion string `pulumi:"azureApiVersion"`
	// Fully qualified resource Id for the resource.
	Id string `pulumi:"id"`
	// The name of the resource.
	Name string `pulumi:"name"`
	// Properties of the Monitoring Setting resource
	Properties MonitoringSettingPropertiesResponse `pulumi:"properties"`
	// Metadata pertaining to creation and last modification of the resource.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// The type of the resource.
	Type string `pulumi:"type"`
}

func LookupMonitoringSettingOutput(ctx *pulumi.Context, args LookupMonitoringSettingOutputArgs, opts ...pulumi.InvokeOption) LookupMonitoringSettingResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupMonitoringSettingResultOutput, error) {
			args := v.(LookupMonitoringSettingArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:appplatform:getMonitoringSetting", args, LookupMonitoringSettingResultOutput{}, options).(LookupMonitoringSettingResultOutput), nil
		}).(LookupMonitoringSettingResultOutput)
}

type LookupMonitoringSettingOutputArgs struct {
	// The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The name of the Service resource.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (LookupMonitoringSettingOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMonitoringSettingArgs)(nil)).Elem()
}

// Monitoring Setting resource
type LookupMonitoringSettingResultOutput struct{ *pulumi.OutputState }

func (LookupMonitoringSettingResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMonitoringSettingResult)(nil)).Elem()
}

func (o LookupMonitoringSettingResultOutput) ToLookupMonitoringSettingResultOutput() LookupMonitoringSettingResultOutput {
	return o
}

func (o LookupMonitoringSettingResultOutput) ToLookupMonitoringSettingResultOutputWithContext(ctx context.Context) LookupMonitoringSettingResultOutput {
	return o
}

// The Azure API version of the resource.
func (o LookupMonitoringSettingResultOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) string { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// Fully qualified resource Id for the resource.
func (o LookupMonitoringSettingResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the resource.
func (o LookupMonitoringSettingResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) string { return v.Name }).(pulumi.StringOutput)
}

// Properties of the Monitoring Setting resource
func (o LookupMonitoringSettingResultOutput) Properties() MonitoringSettingPropertiesResponseOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) MonitoringSettingPropertiesResponse { return v.Properties }).(MonitoringSettingPropertiesResponseOutput)
}

// Metadata pertaining to creation and last modification of the resource.
func (o LookupMonitoringSettingResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource.
func (o LookupMonitoringSettingResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonitoringSettingResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMonitoringSettingResultOutput{})
}
