// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package servicefabric

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get a Service Fabric managed application resource created or in the process of being created in the Service Fabric cluster resource.
// Azure REST API version: 2023-03-01-preview.
func LookupManagedClusterApplication(ctx *pulumi.Context, args *LookupManagedClusterApplicationArgs, opts ...pulumi.InvokeOption) (*LookupManagedClusterApplicationResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupManagedClusterApplicationResult
	err := ctx.Invoke("azure-native:servicefabric:getManagedClusterApplication", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupManagedClusterApplicationArgs struct {
	// The name of the application resource.
	ApplicationName string `pulumi:"applicationName"`
	// The name of the cluster resource.
	ClusterName string `pulumi:"clusterName"`
	// The name of the resource group.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// The application resource.
type LookupManagedClusterApplicationResult struct {
	// Azure resource identifier.
	Id string `pulumi:"id"`
	// Describes the managed identities for an Azure resource.
	Identity *ManagedIdentityResponse `pulumi:"identity"`
	// Resource location depends on the parent resource.
	Location *string `pulumi:"location"`
	// List of user assigned identities for the application, each mapped to a friendly name.
	ManagedIdentities []ApplicationUserAssignedIdentityResponse `pulumi:"managedIdentities"`
	// Azure resource name.
	Name string `pulumi:"name"`
	// List of application parameters with overridden values from their default values specified in the application manifest.
	Parameters map[string]string `pulumi:"parameters"`
	// The current deployment or provisioning state, which only appears in the response
	ProvisioningState string `pulumi:"provisioningState"`
	// Metadata pertaining to creation and last modification of the resource.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// Azure resource tags.
	Tags map[string]string `pulumi:"tags"`
	// Azure resource type.
	Type string `pulumi:"type"`
	// Describes the policy for a monitored application upgrade.
	UpgradePolicy *ApplicationUpgradePolicyResponse `pulumi:"upgradePolicy"`
	// The version of the application type as defined in the application manifest.
	// This name must be the full Arm Resource ID for the referenced application type version.
	Version *string `pulumi:"version"`
}

func LookupManagedClusterApplicationOutput(ctx *pulumi.Context, args LookupManagedClusterApplicationOutputArgs, opts ...pulumi.InvokeOption) LookupManagedClusterApplicationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupManagedClusterApplicationResult, error) {
			args := v.(LookupManagedClusterApplicationArgs)
			r, err := LookupManagedClusterApplication(ctx, &args, opts...)
			var s LookupManagedClusterApplicationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupManagedClusterApplicationResultOutput)
}

type LookupManagedClusterApplicationOutputArgs struct {
	// The name of the application resource.
	ApplicationName pulumi.StringInput `pulumi:"applicationName"`
	// The name of the cluster resource.
	ClusterName pulumi.StringInput `pulumi:"clusterName"`
	// The name of the resource group.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (LookupManagedClusterApplicationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupManagedClusterApplicationArgs)(nil)).Elem()
}

// The application resource.
type LookupManagedClusterApplicationResultOutput struct{ *pulumi.OutputState }

func (LookupManagedClusterApplicationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupManagedClusterApplicationResult)(nil)).Elem()
}

func (o LookupManagedClusterApplicationResultOutput) ToLookupManagedClusterApplicationResultOutput() LookupManagedClusterApplicationResultOutput {
	return o
}

func (o LookupManagedClusterApplicationResultOutput) ToLookupManagedClusterApplicationResultOutputWithContext(ctx context.Context) LookupManagedClusterApplicationResultOutput {
	return o
}

// Azure resource identifier.
func (o LookupManagedClusterApplicationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) string { return v.Id }).(pulumi.StringOutput)
}

// Describes the managed identities for an Azure resource.
func (o LookupManagedClusterApplicationResultOutput) Identity() ManagedIdentityResponsePtrOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) *ManagedIdentityResponse { return v.Identity }).(ManagedIdentityResponsePtrOutput)
}

// Resource location depends on the parent resource.
func (o LookupManagedClusterApplicationResultOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) *string { return v.Location }).(pulumi.StringPtrOutput)
}

// List of user assigned identities for the application, each mapped to a friendly name.
func (o LookupManagedClusterApplicationResultOutput) ManagedIdentities() ApplicationUserAssignedIdentityResponseArrayOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) []ApplicationUserAssignedIdentityResponse {
		return v.ManagedIdentities
	}).(ApplicationUserAssignedIdentityResponseArrayOutput)
}

// Azure resource name.
func (o LookupManagedClusterApplicationResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) string { return v.Name }).(pulumi.StringOutput)
}

// List of application parameters with overridden values from their default values specified in the application manifest.
func (o LookupManagedClusterApplicationResultOutput) Parameters() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) map[string]string { return v.Parameters }).(pulumi.StringMapOutput)
}

// The current deployment or provisioning state, which only appears in the response
func (o LookupManagedClusterApplicationResultOutput) ProvisioningState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) string { return v.ProvisioningState }).(pulumi.StringOutput)
}

// Metadata pertaining to creation and last modification of the resource.
func (o LookupManagedClusterApplicationResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// Azure resource tags.
func (o LookupManagedClusterApplicationResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

// Azure resource type.
func (o LookupManagedClusterApplicationResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) string { return v.Type }).(pulumi.StringOutput)
}

// Describes the policy for a monitored application upgrade.
func (o LookupManagedClusterApplicationResultOutput) UpgradePolicy() ApplicationUpgradePolicyResponsePtrOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) *ApplicationUpgradePolicyResponse {
		return v.UpgradePolicy
	}).(ApplicationUpgradePolicyResponsePtrOutput)
}

// The version of the application type as defined in the application manifest.
// This name must be the full Arm Resource ID for the referenced application type version.
func (o LookupManagedClusterApplicationResultOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupManagedClusterApplicationResult) *string { return v.Version }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupManagedClusterApplicationResultOutput{})
}
