// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20240701preview

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get a DataFlowProfileResource
func LookupDataFlowProfile(ctx *pulumi.Context, args *LookupDataFlowProfileArgs, opts ...pulumi.InvokeOption) (*LookupDataFlowProfileResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupDataFlowProfileResult
	err := ctx.Invoke("azure-native:iotoperations/v20240701preview:getDataFlowProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type LookupDataFlowProfileArgs struct {
	// Name of Instance dataflowProfile resource
	DataflowProfileName string `pulumi:"dataflowProfileName"`
	// Name of instance.
	InstanceName string `pulumi:"instanceName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// Instance dataflowProfile resource
type LookupDataFlowProfileResult struct {
	// Edge location of the resource.
	ExtendedLocation ExtendedLocationResponse `pulumi:"extendedLocation"`
	// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id string `pulumi:"id"`
	// The name of the resource
	Name string `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties DataFlowProfilePropertiesResponse `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type string `pulumi:"type"`
}

// Defaults sets the appropriate defaults for LookupDataFlowProfileResult
func (val *LookupDataFlowProfileResult) Defaults() *LookupDataFlowProfileResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Properties = *tmp.Properties.Defaults()

	return &tmp
}

func LookupDataFlowProfileOutput(ctx *pulumi.Context, args LookupDataFlowProfileOutputArgs, opts ...pulumi.InvokeOption) LookupDataFlowProfileResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDataFlowProfileResultOutput, error) {
			args := v.(LookupDataFlowProfileArgs)
			opts = utilities.PkgInvokeDefaultOpts(opts)
			var rv LookupDataFlowProfileResult
			secret, err := ctx.InvokePackageRaw("azure-native:iotoperations/v20240701preview:getDataFlowProfile", args, &rv, "", opts...)
			if err != nil {
				return LookupDataFlowProfileResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupDataFlowProfileResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupDataFlowProfileResultOutput), nil
			}
			return output, nil
		}).(LookupDataFlowProfileResultOutput)
}

type LookupDataFlowProfileOutputArgs struct {
	// Name of Instance dataflowProfile resource
	DataflowProfileName pulumi.StringInput `pulumi:"dataflowProfileName"`
	// Name of instance.
	InstanceName pulumi.StringInput `pulumi:"instanceName"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (LookupDataFlowProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDataFlowProfileArgs)(nil)).Elem()
}

// Instance dataflowProfile resource
type LookupDataFlowProfileResultOutput struct{ *pulumi.OutputState }

func (LookupDataFlowProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDataFlowProfileResult)(nil)).Elem()
}

func (o LookupDataFlowProfileResultOutput) ToLookupDataFlowProfileResultOutput() LookupDataFlowProfileResultOutput {
	return o
}

func (o LookupDataFlowProfileResultOutput) ToLookupDataFlowProfileResultOutputWithContext(ctx context.Context) LookupDataFlowProfileResultOutput {
	return o
}

// Edge location of the resource.
func (o LookupDataFlowProfileResultOutput) ExtendedLocation() ExtendedLocationResponseOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) ExtendedLocationResponse { return v.ExtendedLocation }).(ExtendedLocationResponseOutput)
}

// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
func (o LookupDataFlowProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the resource
func (o LookupDataFlowProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o LookupDataFlowProfileResultOutput) Properties() DataFlowProfilePropertiesResponseOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) DataFlowProfilePropertiesResponse { return v.Properties }).(DataFlowProfilePropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o LookupDataFlowProfileResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o LookupDataFlowProfileResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDataFlowProfileResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDataFlowProfileResultOutput{})
}
