// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20190101preview

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets the alert rule.
func GetMicrosoftSecurityIncidentCreationAlertRule(ctx *pulumi.Context, args *GetMicrosoftSecurityIncidentCreationAlertRuleArgs, opts ...pulumi.InvokeOption) (*GetMicrosoftSecurityIncidentCreationAlertRuleResult, error) {
	var rv GetMicrosoftSecurityIncidentCreationAlertRuleResult
	err := ctx.Invoke("azure-native:securityinsights/v20190101preview:getMicrosoftSecurityIncidentCreationAlertRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetMicrosoftSecurityIncidentCreationAlertRuleArgs struct {
	// The namespace of workspaces resource provider- Microsoft.OperationalInsights.
	OperationalInsightsResourceProvider string `pulumi:"operationalInsightsResourceProvider"`
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// Alert rule ID
	RuleId string `pulumi:"ruleId"`
	// The name of the workspace.
	WorkspaceName string `pulumi:"workspaceName"`
}

// Represents MicrosoftSecurityIncidentCreation rule.
type GetMicrosoftSecurityIncidentCreationAlertRuleResult struct {
	// The Name of the alert rule template used to create this rule.
	AlertRuleTemplateName *string `pulumi:"alertRuleTemplateName"`
	// The description of the alert rule.
	Description *string `pulumi:"description"`
	// The display name for alerts created by this alert rule.
	DisplayName string `pulumi:"displayName"`
	// the alerts' displayNames on which the cases will not be generated
	DisplayNamesExcludeFilter []string `pulumi:"displayNamesExcludeFilter"`
	// the alerts' displayNames on which the cases will be generated
	DisplayNamesFilter []string `pulumi:"displayNamesFilter"`
	// Determines whether this alert rule is enabled or disabled.
	Enabled bool `pulumi:"enabled"`
	// Etag of the azure resource
	Etag *string `pulumi:"etag"`
	// Azure resource Id
	Id string `pulumi:"id"`
	// Expected value is 'MicrosoftSecurityIncidentCreation'.
	Kind string `pulumi:"kind"`
	// The last time that this alert has been modified.
	LastModifiedUtc string `pulumi:"lastModifiedUtc"`
	// Azure resource name
	Name string `pulumi:"name"`
	// The alerts' productName on which the cases will be generated
	ProductFilter string `pulumi:"productFilter"`
	// the alerts' severities on which the cases will be generated
	SeveritiesFilter []string `pulumi:"severitiesFilter"`
	// Azure resource type
	Type string `pulumi:"type"`
}

func GetMicrosoftSecurityIncidentCreationAlertRuleOutput(ctx *pulumi.Context, args GetMicrosoftSecurityIncidentCreationAlertRuleOutputArgs, opts ...pulumi.InvokeOption) GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMicrosoftSecurityIncidentCreationAlertRuleResult, error) {
			args := v.(GetMicrosoftSecurityIncidentCreationAlertRuleArgs)
			r, err := GetMicrosoftSecurityIncidentCreationAlertRule(ctx, &args, opts...)
			var s GetMicrosoftSecurityIncidentCreationAlertRuleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput)
}

type GetMicrosoftSecurityIncidentCreationAlertRuleOutputArgs struct {
	// The namespace of workspaces resource provider- Microsoft.OperationalInsights.
	OperationalInsightsResourceProvider pulumi.StringInput `pulumi:"operationalInsightsResourceProvider"`
	// The name of the resource group within the user's subscription. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// Alert rule ID
	RuleId pulumi.StringInput `pulumi:"ruleId"`
	// The name of the workspace.
	WorkspaceName pulumi.StringInput `pulumi:"workspaceName"`
}

func (GetMicrosoftSecurityIncidentCreationAlertRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMicrosoftSecurityIncidentCreationAlertRuleArgs)(nil)).Elem()
}

// Represents MicrosoftSecurityIncidentCreation rule.
type GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput struct{ *pulumi.OutputState }

func (GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMicrosoftSecurityIncidentCreationAlertRuleResult)(nil)).Elem()
}

func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) ToGetMicrosoftSecurityIncidentCreationAlertRuleResultOutput() GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput {
	return o
}

func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) ToGetMicrosoftSecurityIncidentCreationAlertRuleResultOutputWithContext(ctx context.Context) GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput {
	return o
}

// The Name of the alert rule template used to create this rule.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) AlertRuleTemplateName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) *string { return v.AlertRuleTemplateName }).(pulumi.StringPtrOutput)
}

// The description of the alert rule.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The display name for alerts created by this alert rule.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// the alerts' displayNames on which the cases will not be generated
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) DisplayNamesExcludeFilter() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) []string {
		return v.DisplayNamesExcludeFilter
	}).(pulumi.StringArrayOutput)
}

// the alerts' displayNames on which the cases will be generated
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) DisplayNamesFilter() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) []string { return v.DisplayNamesFilter }).(pulumi.StringArrayOutput)
}

// Determines whether this alert rule is enabled or disabled.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Etag of the azure resource
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Etag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) *string { return v.Etag }).(pulumi.StringPtrOutput)
}

// Azure resource Id
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Expected value is 'MicrosoftSecurityIncidentCreation'.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.Kind }).(pulumi.StringOutput)
}

// The last time that this alert has been modified.
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) LastModifiedUtc() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.LastModifiedUtc }).(pulumi.StringOutput)
}

// Azure resource name
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.Name }).(pulumi.StringOutput)
}

// The alerts' productName on which the cases will be generated
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) ProductFilter() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.ProductFilter }).(pulumi.StringOutput)
}

// the alerts' severities on which the cases will be generated
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) SeveritiesFilter() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) []string { return v.SeveritiesFilter }).(pulumi.StringArrayOutput)
}

// Azure resource type
func (o GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetMicrosoftSecurityIncidentCreationAlertRuleResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMicrosoftSecurityIncidentCreationAlertRuleResultOutput{})
}
