// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package authorization

import (
	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This operation lists all the built-in policy set definition versions for all built-in policy set definitions.
// Azure REST API version: 2023-04-01.
func ListPolicySetDefinitionVersionAllBuiltins(ctx *pulumi.Context, args *ListPolicySetDefinitionVersionAllBuiltinsArgs, opts ...pulumi.InvokeOption) (*ListPolicySetDefinitionVersionAllBuiltinsResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv ListPolicySetDefinitionVersionAllBuiltinsResult
	err := ctx.Invoke("azure-native:authorization:listPolicySetDefinitionVersionAllBuiltins", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListPolicySetDefinitionVersionAllBuiltinsArgs struct {
}

// List of policy set definition versions.
type ListPolicySetDefinitionVersionAllBuiltinsResult struct {
	// The URL to use for getting the next set of results.
	NextLink *string `pulumi:"nextLink"`
	// An array of policy set definition versions.
	Value []PolicySetDefinitionVersionResponse `pulumi:"value"`
}
