// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awsconnector

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Microsoft.AwsConnector resource
// Azure REST API version: 2024-12-01. Prior API version in Azure Native 2.x: 2024-12-01.
type S3AccessControlPolicy struct {
	pulumi.CustomResourceState

	// The Azure API version of the resource.
	AzureApiVersion pulumi.StringOutput `pulumi:"azureApiVersion"`
	// The geo-location where the resource lives
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of the resource
	Name pulumi.StringOutput `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties S3AccessControlPolicyPropertiesResponseOutput `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponseOutput `pulumi:"systemData"`
	// Resource tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewS3AccessControlPolicy registers a new resource with the given unique name, arguments, and options.
func NewS3AccessControlPolicy(ctx *pulumi.Context,
	name string, args *S3AccessControlPolicyArgs, opts ...pulumi.ResourceOption) (*S3AccessControlPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type: pulumi.String("azure-native:awsconnector/v20241201:S3AccessControlPolicy"),
		},
	})
	opts = append(opts, aliases)
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource S3AccessControlPolicy
	err := ctx.RegisterResource("azure-native:awsconnector:S3AccessControlPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3AccessControlPolicy gets an existing S3AccessControlPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3AccessControlPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3AccessControlPolicyState, opts ...pulumi.ResourceOption) (*S3AccessControlPolicy, error) {
	var resource S3AccessControlPolicy
	err := ctx.ReadResource("azure-native:awsconnector:S3AccessControlPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3AccessControlPolicy resources.
type s3accessControlPolicyState struct {
}

type S3AccessControlPolicyState struct {
}

func (S3AccessControlPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3accessControlPolicyState)(nil)).Elem()
}

type s3accessControlPolicyArgs struct {
	// The geo-location where the resource lives
	Location *string `pulumi:"location"`
	// Name of S3AccessControlPolicy
	Name *string `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties *S3AccessControlPolicyProperties `pulumi:"properties"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// Resource tags.
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a S3AccessControlPolicy resource.
type S3AccessControlPolicyArgs struct {
	// The geo-location where the resource lives
	Location pulumi.StringPtrInput
	// Name of S3AccessControlPolicy
	Name pulumi.StringPtrInput
	// The resource-specific properties for this resource.
	Properties S3AccessControlPolicyPropertiesPtrInput
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput
	// Resource tags.
	Tags pulumi.StringMapInput
}

func (S3AccessControlPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3accessControlPolicyArgs)(nil)).Elem()
}

type S3AccessControlPolicyInput interface {
	pulumi.Input

	ToS3AccessControlPolicyOutput() S3AccessControlPolicyOutput
	ToS3AccessControlPolicyOutputWithContext(ctx context.Context) S3AccessControlPolicyOutput
}

func (*S3AccessControlPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**S3AccessControlPolicy)(nil)).Elem()
}

func (i *S3AccessControlPolicy) ToS3AccessControlPolicyOutput() S3AccessControlPolicyOutput {
	return i.ToS3AccessControlPolicyOutputWithContext(context.Background())
}

func (i *S3AccessControlPolicy) ToS3AccessControlPolicyOutputWithContext(ctx context.Context) S3AccessControlPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3AccessControlPolicyOutput)
}

type S3AccessControlPolicyOutput struct{ *pulumi.OutputState }

func (S3AccessControlPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3AccessControlPolicy)(nil)).Elem()
}

func (o S3AccessControlPolicyOutput) ToS3AccessControlPolicyOutput() S3AccessControlPolicyOutput {
	return o
}

func (o S3AccessControlPolicyOutput) ToS3AccessControlPolicyOutputWithContext(ctx context.Context) S3AccessControlPolicyOutput {
	return o
}

// The Azure API version of the resource.
func (o S3AccessControlPolicyOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) pulumi.StringOutput { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// The geo-location where the resource lives
func (o S3AccessControlPolicyOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of the resource
func (o S3AccessControlPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o S3AccessControlPolicyOutput) Properties() S3AccessControlPolicyPropertiesResponseOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) S3AccessControlPolicyPropertiesResponseOutput { return v.Properties }).(S3AccessControlPolicyPropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o S3AccessControlPolicyOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) SystemDataResponseOutput { return v.SystemData }).(SystemDataResponseOutput)
}

// Resource tags.
func (o S3AccessControlPolicyOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o S3AccessControlPolicyOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *S3AccessControlPolicy) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(S3AccessControlPolicyOutput{})
}
