// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v20250401preview

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get firmware.
func LookupFirmware(ctx *pulumi.Context, args *LookupFirmwareArgs, opts ...pulumi.InvokeOption) (*LookupFirmwareResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupFirmwareResult
	err := ctx.Invoke("azure-native:iotfirmwaredefense/v20250401preview:getFirmware", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupFirmwareArgs struct {
	// The id of the firmware.
	FirmwareId string `pulumi:"firmwareId"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The name of the firmware analysis workspace.
	WorkspaceName string `pulumi:"workspaceName"`
}

// Firmware definition
type LookupFirmwareResult struct {
	// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id string `pulumi:"id"`
	// The name of the resource
	Name string `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties FirmwarePropertiesResponse `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type string `pulumi:"type"`
}

func LookupFirmwareOutput(ctx *pulumi.Context, args LookupFirmwareOutputArgs, opts ...pulumi.InvokeOption) LookupFirmwareResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFirmwareResultOutput, error) {
			args := v.(LookupFirmwareArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:iotfirmwaredefense/v20250401preview:getFirmware", args, LookupFirmwareResultOutput{}, options).(LookupFirmwareResultOutput), nil
		}).(LookupFirmwareResultOutput)
}

type LookupFirmwareOutputArgs struct {
	// The id of the firmware.
	FirmwareId pulumi.StringInput `pulumi:"firmwareId"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The name of the firmware analysis workspace.
	WorkspaceName pulumi.StringInput `pulumi:"workspaceName"`
}

func (LookupFirmwareOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFirmwareArgs)(nil)).Elem()
}

// Firmware definition
type LookupFirmwareResultOutput struct{ *pulumi.OutputState }

func (LookupFirmwareResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFirmwareResult)(nil)).Elem()
}

func (o LookupFirmwareResultOutput) ToLookupFirmwareResultOutput() LookupFirmwareResultOutput {
	return o
}

func (o LookupFirmwareResultOutput) ToLookupFirmwareResultOutputWithContext(ctx context.Context) LookupFirmwareResultOutput {
	return o
}

// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
func (o LookupFirmwareResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirmwareResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the resource
func (o LookupFirmwareResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirmwareResult) string { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o LookupFirmwareResultOutput) Properties() FirmwarePropertiesResponseOutput {
	return o.ApplyT(func(v LookupFirmwareResult) FirmwarePropertiesResponse { return v.Properties }).(FirmwarePropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o LookupFirmwareResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupFirmwareResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o LookupFirmwareResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirmwareResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFirmwareResultOutput{})
}
