// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package eventgrid

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get properties of a client.
//
// Uses Azure REST API version 2025-02-15.
//
// Other available API versions: 2023-06-01-preview, 2023-12-15-preview, 2024-06-01-preview, 2024-12-15-preview, 2025-04-01-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native eventgrid [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
func LookupClient(ctx *pulumi.Context, args *LookupClientArgs, opts ...pulumi.InvokeOption) (*LookupClientResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupClientResult
	err := ctx.Invoke("azure-native:eventgrid:getClient", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type LookupClientArgs struct {
	// Name of the client.
	ClientName string `pulumi:"clientName"`
	// Name of the namespace.
	NamespaceName string `pulumi:"namespaceName"`
	// The name of the resource group within the user's subscription.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// The Client resource.
type LookupClientResult struct {
	// Attributes for the client. Supported values are int, bool, string, string[].
	// Example:
	// "attributes": { "room": "345", "floor": 12, "deviceTypes": ["Fan", "Light"] }
	Attributes interface{} `pulumi:"attributes"`
	// The name presented by the client for authentication. The default value is the name of the resource.
	AuthenticationName *string `pulumi:"authenticationName"`
	// The Azure API version of the resource.
	AzureApiVersion string `pulumi:"azureApiVersion"`
	// The client certificate authentication information.
	ClientCertificateAuthentication *ClientCertificateAuthenticationResponse `pulumi:"clientCertificateAuthentication"`
	// Description for the Client resource.
	Description *string `pulumi:"description"`
	// Fully qualified identifier of the resource.
	Id string `pulumi:"id"`
	// Name of the resource.
	Name string `pulumi:"name"`
	// Provisioning state of the Client resource.
	ProvisioningState string `pulumi:"provisioningState"`
	// Indicates if the client is enabled or not. Default value is Enabled.
	State *string `pulumi:"state"`
	// The system metadata relating to the Event Grid resource.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// Type of the resource.
	Type string `pulumi:"type"`
}

// Defaults sets the appropriate defaults for LookupClientResult
func (val *LookupClientResult) Defaults() *LookupClientResult {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.State == nil {
		state_ := "Enabled"
		tmp.State = &state_
	}
	return &tmp
}
func LookupClientOutput(ctx *pulumi.Context, args LookupClientOutputArgs, opts ...pulumi.InvokeOption) LookupClientResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupClientResultOutput, error) {
			args := v.(LookupClientArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:eventgrid:getClient", args, LookupClientResultOutput{}, options).(LookupClientResultOutput), nil
		}).(LookupClientResultOutput)
}

type LookupClientOutputArgs struct {
	// Name of the client.
	ClientName pulumi.StringInput `pulumi:"clientName"`
	// Name of the namespace.
	NamespaceName pulumi.StringInput `pulumi:"namespaceName"`
	// The name of the resource group within the user's subscription.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
}

func (LookupClientOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientArgs)(nil)).Elem()
}

// The Client resource.
type LookupClientResultOutput struct{ *pulumi.OutputState }

func (LookupClientResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientResult)(nil)).Elem()
}

func (o LookupClientResultOutput) ToLookupClientResultOutput() LookupClientResultOutput {
	return o
}

func (o LookupClientResultOutput) ToLookupClientResultOutputWithContext(ctx context.Context) LookupClientResultOutput {
	return o
}

// Attributes for the client. Supported values are int, bool, string, string[].
// Example:
// "attributes": { "room": "345", "floor": 12, "deviceTypes": ["Fan", "Light"] }
func (o LookupClientResultOutput) Attributes() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupClientResult) interface{} { return v.Attributes }).(pulumi.AnyOutput)
}

// The name presented by the client for authentication. The default value is the name of the resource.
func (o LookupClientResultOutput) AuthenticationName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupClientResult) *string { return v.AuthenticationName }).(pulumi.StringPtrOutput)
}

// The Azure API version of the resource.
func (o LookupClientResultOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientResult) string { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// The client certificate authentication information.
func (o LookupClientResultOutput) ClientCertificateAuthentication() ClientCertificateAuthenticationResponsePtrOutput {
	return o.ApplyT(func(v LookupClientResult) *ClientCertificateAuthenticationResponse {
		return v.ClientCertificateAuthentication
	}).(ClientCertificateAuthenticationResponsePtrOutput)
}

// Description for the Client resource.
func (o LookupClientResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupClientResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Fully qualified identifier of the resource.
func (o LookupClientResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientResult) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the resource.
func (o LookupClientResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientResult) string { return v.Name }).(pulumi.StringOutput)
}

// Provisioning state of the Client resource.
func (o LookupClientResultOutput) ProvisioningState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientResult) string { return v.ProvisioningState }).(pulumi.StringOutput)
}

// Indicates if the client is enabled or not. Default value is Enabled.
func (o LookupClientResultOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupClientResult) *string { return v.State }).(pulumi.StringPtrOutput)
}

// The system metadata relating to the Event Grid resource.
func (o LookupClientResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupClientResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// Type of the resource.
func (o LookupClientResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupClientResultOutput{})
}
