// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package edge

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Schema Reference Resource
//
// Uses Azure REST API version 2025-08-01.
//
// Other available API versions: 2025-06-01. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native edge [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
type SchemaReference struct {
	pulumi.CustomResourceState

	// The Azure API version of the resource.
	AzureApiVersion pulumi.StringOutput `pulumi:"azureApiVersion"`
	// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
	ETag pulumi.StringOutput `pulumi:"eTag"`
	// The name of the resource
	Name pulumi.StringOutput `pulumi:"name"`
	// The resource-specific properties for this resource.
	Properties SchemaReferencePropertiesResponseOutput `pulumi:"properties"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponseOutput `pulumi:"systemData"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewSchemaReference registers a new resource with the given unique name, arguments, and options.
func NewSchemaReference(ctx *pulumi.Context,
	name string, args *SchemaReferenceArgs, opts ...pulumi.ResourceOption) (*SchemaReference, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ResourceUri == nil {
		return nil, errors.New("invalid value for required argument 'ResourceUri'")
	}
	aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type: pulumi.String("azure-native:edge/v20250601:SchemaReference"),
		},
		{
			Type: pulumi.String("azure-native:edge/v20250801:SchemaReference"),
		},
	})
	opts = append(opts, aliases)
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource SchemaReference
	err := ctx.RegisterResource("azure-native:edge:SchemaReference", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchemaReference gets an existing SchemaReference resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchemaReference(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SchemaReferenceState, opts ...pulumi.ResourceOption) (*SchemaReference, error) {
	var resource SchemaReference
	err := ctx.ReadResource("azure-native:edge:SchemaReference", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SchemaReference resources.
type schemaReferenceState struct {
}

type SchemaReferenceState struct {
}

func (SchemaReferenceState) ElementType() reflect.Type {
	return reflect.TypeOf((*schemaReferenceState)(nil)).Elem()
}

type schemaReferenceArgs struct {
	// The resource-specific properties for this resource.
	Properties *SchemaReferenceProperties `pulumi:"properties"`
	// The fully qualified Azure Resource manager identifier of the resource.
	ResourceUri string `pulumi:"resourceUri"`
	// The name of the SchemaReference
	SchemaReferenceName *string `pulumi:"schemaReferenceName"`
}

// The set of arguments for constructing a SchemaReference resource.
type SchemaReferenceArgs struct {
	// The resource-specific properties for this resource.
	Properties SchemaReferencePropertiesPtrInput
	// The fully qualified Azure Resource manager identifier of the resource.
	ResourceUri pulumi.StringInput
	// The name of the SchemaReference
	SchemaReferenceName pulumi.StringPtrInput
}

func (SchemaReferenceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*schemaReferenceArgs)(nil)).Elem()
}

type SchemaReferenceInput interface {
	pulumi.Input

	ToSchemaReferenceOutput() SchemaReferenceOutput
	ToSchemaReferenceOutputWithContext(ctx context.Context) SchemaReferenceOutput
}

func (*SchemaReference) ElementType() reflect.Type {
	return reflect.TypeOf((**SchemaReference)(nil)).Elem()
}

func (i *SchemaReference) ToSchemaReferenceOutput() SchemaReferenceOutput {
	return i.ToSchemaReferenceOutputWithContext(context.Background())
}

func (i *SchemaReference) ToSchemaReferenceOutputWithContext(ctx context.Context) SchemaReferenceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SchemaReferenceOutput)
}

type SchemaReferenceOutput struct{ *pulumi.OutputState }

func (SchemaReferenceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SchemaReference)(nil)).Elem()
}

func (o SchemaReferenceOutput) ToSchemaReferenceOutput() SchemaReferenceOutput {
	return o
}

func (o SchemaReferenceOutput) ToSchemaReferenceOutputWithContext(ctx context.Context) SchemaReferenceOutput {
	return o
}

// The Azure API version of the resource.
func (o SchemaReferenceOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *SchemaReference) pulumi.StringOutput { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
func (o SchemaReferenceOutput) ETag() pulumi.StringOutput {
	return o.ApplyT(func(v *SchemaReference) pulumi.StringOutput { return v.ETag }).(pulumi.StringOutput)
}

// The name of the resource
func (o SchemaReferenceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SchemaReference) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The resource-specific properties for this resource.
func (o SchemaReferenceOutput) Properties() SchemaReferencePropertiesResponseOutput {
	return o.ApplyT(func(v *SchemaReference) SchemaReferencePropertiesResponseOutput { return v.Properties }).(SchemaReferencePropertiesResponseOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o SchemaReferenceOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v *SchemaReference) SystemDataResponseOutput { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o SchemaReferenceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *SchemaReference) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(SchemaReferenceOutput{})
}
