// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package apimanagement

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v2/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets the secret of the named value specified by its identifier.
// Azure REST API version: 2022-09-01-preview.
//
// Other available API versions: 2023-03-01-preview, 2023-05-01-preview, 2023-09-01-preview, 2024-05-01.
func ListWorkspaceNamedValue(ctx *pulumi.Context, args *ListWorkspaceNamedValueArgs, opts ...pulumi.InvokeOption) (*ListWorkspaceNamedValueResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv ListWorkspaceNamedValueResult
	err := ctx.Invoke("azure-native:apimanagement:listWorkspaceNamedValue", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListWorkspaceNamedValueArgs struct {
	// Identifier of the NamedValue.
	NamedValueId string `pulumi:"namedValueId"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The name of the API Management service.
	ServiceName string `pulumi:"serviceName"`
	// Workspace identifier. Must be unique in the current API Management service instance.
	WorkspaceId string `pulumi:"workspaceId"`
}

// Client or app secret used in IdentityProviders, Aad, OpenID or OAuth.
type ListWorkspaceNamedValueResult struct {
	// This is secret value of the NamedValue entity.
	Value *string `pulumi:"value"`
}

func ListWorkspaceNamedValueOutput(ctx *pulumi.Context, args ListWorkspaceNamedValueOutputArgs, opts ...pulumi.InvokeOption) ListWorkspaceNamedValueResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListWorkspaceNamedValueResultOutput, error) {
			args := v.(ListWorkspaceNamedValueArgs)
			opts = utilities.PkgInvokeDefaultOpts(opts)
			var rv ListWorkspaceNamedValueResult
			secret, err := ctx.InvokePackageRaw("azure-native:apimanagement:listWorkspaceNamedValue", args, &rv, "", opts...)
			if err != nil {
				return ListWorkspaceNamedValueResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(ListWorkspaceNamedValueResultOutput)
			if secret {
				return pulumi.ToSecret(output).(ListWorkspaceNamedValueResultOutput), nil
			}
			return output, nil
		}).(ListWorkspaceNamedValueResultOutput)
}

type ListWorkspaceNamedValueOutputArgs struct {
	// Identifier of the NamedValue.
	NamedValueId pulumi.StringInput `pulumi:"namedValueId"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// The name of the API Management service.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
	// Workspace identifier. Must be unique in the current API Management service instance.
	WorkspaceId pulumi.StringInput `pulumi:"workspaceId"`
}

func (ListWorkspaceNamedValueOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListWorkspaceNamedValueArgs)(nil)).Elem()
}

// Client or app secret used in IdentityProviders, Aad, OpenID or OAuth.
type ListWorkspaceNamedValueResultOutput struct{ *pulumi.OutputState }

func (ListWorkspaceNamedValueResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListWorkspaceNamedValueResult)(nil)).Elem()
}

func (o ListWorkspaceNamedValueResultOutput) ToListWorkspaceNamedValueResultOutput() ListWorkspaceNamedValueResultOutput {
	return o
}

func (o ListWorkspaceNamedValueResultOutput) ToListWorkspaceNamedValueResultOutputWithContext(ctx context.Context) ListWorkspaceNamedValueResultOutput {
	return o
}

// This is secret value of the NamedValue entity.
func (o ListWorkspaceNamedValueResultOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListWorkspaceNamedValueResult) *string { return v.Value }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ListWorkspaceNamedValueResultOutput{})
}
