// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package web

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-azure-native-sdk/v3/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Description for Get domain ownership identifier for web app.
//
// Uses Azure REST API version 2025-05-01.
//
// Other available API versions: 2016-08-01, 2018-02-01, 2018-11-01, 2019-08-01, 2020-06-01, 2020-09-01, 2020-10-01, 2020-12-01, 2021-01-01, 2021-01-15, 2021-02-01, 2021-03-01, 2022-03-01, 2022-09-01, 2023-01-01, 2023-12-01, 2024-04-01, 2024-11-01, 2025-03-01, 2026-03-01-preview, 2026-03-15. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native web [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
func LookupWebAppDomainOwnershipIdentifierSlot(ctx *pulumi.Context, args *LookupWebAppDomainOwnershipIdentifierSlotArgs, opts ...pulumi.InvokeOption) (*LookupWebAppDomainOwnershipIdentifierSlotResult, error) {
	opts = utilities.PkgInvokeDefaultOpts(opts)
	var rv LookupWebAppDomainOwnershipIdentifierSlotResult
	err := ctx.Invoke("azure-native:web:getWebAppDomainOwnershipIdentifierSlot", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupWebAppDomainOwnershipIdentifierSlotArgs struct {
	// Name of domain ownership identifier.
	DomainOwnershipIdentifierName string `pulumi:"domainOwnershipIdentifierName"`
	// Name of the app.
	Name string `pulumi:"name"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// Name of the deployment slot. If a slot is not specified, the API will delete the binding for the production slot.
	Slot string `pulumi:"slot"`
}

// A domain specific resource identifier.
type LookupWebAppDomainOwnershipIdentifierSlotResult struct {
	// The Azure API version of the resource.
	AzureApiVersion string `pulumi:"azureApiVersion"`
	// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id string `pulumi:"id"`
	// Kind of resource.
	Kind *string `pulumi:"kind"`
	// The name of the resource
	Name string `pulumi:"name"`
	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData SystemDataResponse `pulumi:"systemData"`
	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type string `pulumi:"type"`
	// String representation of the identity.
	Value *string `pulumi:"value"`
}

func LookupWebAppDomainOwnershipIdentifierSlotOutput(ctx *pulumi.Context, args LookupWebAppDomainOwnershipIdentifierSlotOutputArgs, opts ...pulumi.InvokeOption) LookupWebAppDomainOwnershipIdentifierSlotResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupWebAppDomainOwnershipIdentifierSlotResultOutput, error) {
			args := v.(LookupWebAppDomainOwnershipIdentifierSlotArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: utilities.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azure-native:web:getWebAppDomainOwnershipIdentifierSlot", args, LookupWebAppDomainOwnershipIdentifierSlotResultOutput{}, options).(LookupWebAppDomainOwnershipIdentifierSlotResultOutput), nil
		}).(LookupWebAppDomainOwnershipIdentifierSlotResultOutput)
}

type LookupWebAppDomainOwnershipIdentifierSlotOutputArgs struct {
	// Name of domain ownership identifier.
	DomainOwnershipIdentifierName pulumi.StringInput `pulumi:"domainOwnershipIdentifierName"`
	// Name of the app.
	Name pulumi.StringInput `pulumi:"name"`
	// The name of the resource group. The name is case insensitive.
	ResourceGroupName pulumi.StringInput `pulumi:"resourceGroupName"`
	// Name of the deployment slot. If a slot is not specified, the API will delete the binding for the production slot.
	Slot pulumi.StringInput `pulumi:"slot"`
}

func (LookupWebAppDomainOwnershipIdentifierSlotOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupWebAppDomainOwnershipIdentifierSlotArgs)(nil)).Elem()
}

// A domain specific resource identifier.
type LookupWebAppDomainOwnershipIdentifierSlotResultOutput struct{ *pulumi.OutputState }

func (LookupWebAppDomainOwnershipIdentifierSlotResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupWebAppDomainOwnershipIdentifierSlotResult)(nil)).Elem()
}

func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) ToLookupWebAppDomainOwnershipIdentifierSlotResultOutput() LookupWebAppDomainOwnershipIdentifierSlotResultOutput {
	return o
}

func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) ToLookupWebAppDomainOwnershipIdentifierSlotResultOutputWithContext(ctx context.Context) LookupWebAppDomainOwnershipIdentifierSlotResultOutput {
	return o
}

// The Azure API version of the resource.
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) AzureApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) string { return v.AzureApiVersion }).(pulumi.StringOutput)
}

// Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) string { return v.Id }).(pulumi.StringOutput)
}

// Kind of resource.
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

// The name of the resource
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) string { return v.Name }).(pulumi.StringOutput)
}

// Azure Resource Manager metadata containing createdBy and modifiedBy information.
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) SystemData() SystemDataResponseOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) SystemDataResponse { return v.SystemData }).(SystemDataResponseOutput)
}

// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) string { return v.Type }).(pulumi.StringOutput)
}

// String representation of the identity.
func (o LookupWebAppDomainOwnershipIdentifierSlotResultOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupWebAppDomainOwnershipIdentifierSlotResult) *string { return v.Value }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupWebAppDomainOwnershipIdentifierSlotResultOutput{})
}
